### ISSUE TITLE
Escape $ symbol in expression.

### ISSUE THREAD

**Issue by 0ffer** [schibsted/jslt#102]
Hello! 
I'm try to use JSLT expression to prepare GraphQL query.
But in GraphQL syntax symbol '$' already used to resolve own variables.
Can I do something with it?
May be I can change JSLT variable token or use some already exists escape functionality?

**Comment by larsga** [comment]
I'm not sure I understand the problem. You want to output `$`?

Write `"$hey"` and the output will be `"$hey"`.

I think you need to be clear on whether you are sending JSLT to GraphQL so that `$`s in JSLT need to be escaped, or vice versa.

**Comment by 0ffer** [comment]
I apologize. I wasn't paying attention.
We have queries like this:
```
{
  "query": "query GetBalance($id: Long!) { getBalance(customerAccountId: $id) {amount currencyCode}",
  "variables": {
    "id": ${queryParams.accountId}
  }
}
```
I didn't see that "query" is a string.
I consider JSLT as a replacement for "$ {} " self-written logic.
Thank you for such a quick response.
