### ISSUE TITLE
Object matching with subobjects

### ISSUE THREAD

**Issue by wdonne** [schibsted/jslt#104]
Hello,

Currently you can copy the keys and their values from the input object with "*: ."  What if the construction of the output object should be based on some subobject? Say you have the following input object:

`{
    "a": 0,
    "b": {
      "c": 1,
      "d": 2
    }
}`

The output should be this:

`{
    "c": 1,
    "d": 2
}`

It would be nice to be able to write the following to achieve this:

`{
    .b.*: .
}`

Best regards,

Werner.

**Comment by larsga** [comment]
I'm not sure I understand what you want to do. You could get the output you describe by simply doing:

`.b`

Somehow I don't think that's what you mean, but I'm kind of confused about what you do want. Is the idea to take the content of the `b` key and rewrite it?

**Comment by wdonne** [comment]
Indeed writing ```.b``` gives you that element, but in this case you want to get this element and then overwrite or add fields to it, which is now only possible for the top-level object. My example is indeed not clear. If I write this:

`{ .b.*: ., "d": 3, "e": 4}`

Then the output would be:

`{"c": 1, "d": 3, "e": 4}`

**Comment by larsga** [comment]
Ah, I see. Yes, this makes sense. This works in JSLT now:

```
{
  "b" : {
    "d" : 3,
    "e" : 4,
    * : .
  },
  * : .
}
```

It's not really much longer than your proposal, and IMHO clearer.

**Comment by wdonne** [comment]
But then the output object has the field "b", while it should only contain the fields within "b", plus whatever was added.

**Comment by larsga** [comment]
Now I'm with you. Yes, this is a missing feature. I was thinking of extending the language to allow this:

```
.b | {
    "d" : 3,
    "e" : 4,
    * : .
  }
```

The pipe changes the context node so that the object matching happens on the value of `.b`.

What do you think?

**Comment by wdonne** [comment]
In fact, that is clearer and the pipe operator can be used in other situations as well. Thanks!

**Comment by larsga** [comment]
I need to go through my notes again and double-check, but I think this is something I want to implement.

**Comment by ecerulm** [comment]
We originally discussed the pipe operator in issue #40
