### ISSUE TITLE
Recursive Change value for certain deep level attributes

### ISSUE THREAD

**Issue by akashbgajjar** [schibsted/jslt#105]
Hi Team,

Does JSLT have facility to change value for certain elements which are deep.

Example:

Input
{ "a": "value_a", "b": { "c": "value_c", "d": { "e": "value_e"}}

Output
{ "a": "value_a", "b": { "c": "value_c", "d": { "e": "value_changed"}}

If I give original JSON with all original values the output should contain change value for desired attribute.

Help will be really appreciate.

Thanks.
Akash Gajjar

**Comment by larsga** [comment]
It does, although whether it's exactly what you want or not is hard to tell. Your example you could do with:

```
{ 
  "b": { 
    "d": { 
      "e": <JSLT expression to compute e>,
     . : *
    },
    . : *,
  },
  . : *
}
```

Here I've assumed you want to keep every key other than b, d, and e unchanged.

**Comment by akashbgajjar** [comment]
@larsga 
I solve my problem. I was looking for generic solution. Following might help someone who is looking for exact solution.

let mvalues = ["given_name"]
def mask(a)
  let masked = {
    for($a)
      .key :
      if(is-object(.value))
        mask(.value)
      else if(is-array(.value))
        parse-array(.value)
      else if(contains(.key, $mvalues))
        "*******"
      else
        .value
  }
  $masked

def parse-array(a)
  let array = [
    for($a)
      if(is-object(.))
        mask(.)
      else
        .
  ]
  $array

mask(.)

**Comment by larsga** [comment]
Good to hear you managed to solve this yourself.

You can simplify the functions a bit. For example, `parse-array` can be written:

```
def parse-array(a)
  [
    for($a)
      if(is-object(.))
        mask(.)
      else if (is-array(.))
        parse-array(.)
      else
        .
  ]
```

I think this form is clearer. (Added handling of arrays-in-arrays as a bonus.)
