### ISSUE TITLE
Add parse_url function

### ISSUE THREAD

**Issue by ecerulm** [schibsted/jslt#106]
Consider adding a function `parse_url()` so that it decomposes the url in it's component as a JSON object. 

To illustrate: 

The following JSTL expression 

```
parse_url('https://www.aftonbladet.se/nyheter/a/opyK1R/snosmocka-pa-ingang--kan-bli-20-centimeter?utm_source=aaaa&utm_campaign=bbbb&utm_medium=cccc&utm_content=dddd&utm_term=eeee')
```
would evaluate to 

```
{
  "fragment": null,
  "host": "www.aftonbladet.se",
  "parameters": {
    "utm_campaign": "bbbb",
    "utm_content": "dddd",
    "utm_medium": "cccc",
    "utm_source": "aaaa",
    "utm_term": "eeee"
  },
  "path": "nyheter/a/opyK1R/snosmocka-pa-ingang--kan-bli-20-centimeter",
  "port": null,
  "query": "utm_source=aaaa&utm_campaign=bbbb&utm_medium=cccc&utm_content=dddd&utm_term=eeee",
  "scheme": "https"
}
```

Use case: This function would allow to write transformations that extract UTM tags from the URL.

**Comment by larsga** [comment]
Hmmmmm. I guess one risk is that we end up growing the standard library too much. On the other hand, this probably *is* something that is needed quite often. And it's difficult to do correctly in JSLT.

I see jq had [a request to add this function](https://github.com/stedolan/jq/issues/537), but in the end they seem not to have done it.

Another risk is that we might not structure the output correctly. I've thought a bit about the structure the response should have, and decided on the same structure you've got in your example, so that should be OK.

What should be the output of these examples?

```
parse-url("mailto:larsga@garshol.priv.no")
parse-url("urn:isbn:0451450523")
parse-url("ftp://somehost.org/path/to/file.txt")
```

I think I'm in favour of the proposal, but let's work through all the angles first.

**Comment by ecerulm** [comment]
The [PARSE_URL](https://docs.snowflake.net/manuals/sql-reference/functions/parse_url.html) function in Snowflake SQL gives the following result for those inputs
```
parse-url("mailto:larsga@garshol.priv.no")
{
  "fragment": null,
  "host": null,
  "parameters": null,
  "path": "larsga@garshol.priv.no",
  "port": null,
  "query": null,
  "scheme": "mailto"
}


parse-url("urn:isbn:0451450523")
{
  "fragment": null,
  "host": null,
  "parameters": null,
  "path": "isbn:0451450523",
  "port": null,
  "query": null,
  "scheme": "urn"
}

parse-url("ftp://somehost.org/path/to/file.txt")
{
  "fragment": null,
  "host": "somehost.org",
  "parameters": null,
  "path": "path/to/file.txt",
  "port": null,
  "query": null,
  "scheme": "ftp"
}
```

But I guess that `urn:isbn:0451450523` is not really a URL , just a URN (not all URNs are URLs).  https://stackoverflow.com/a/4913371/90580. 

I'll   try the same thing with [python's urllib.parse](https://docs.python.org/3/library/urllib.parse.html) and post it here

**Comment by catull** [comment]
A bit late to the party.

I have 2 observations.

1. This sort of functionality could be factored out, say into `jstl-addon` / `jstl-extra`.

2. This request in IMHO can be implemented with some regexp trickery.
     Is it not a String -> struct transformation ?
     In simple terms, there are a handful of schemata, which end just before the colon.
     Those would be: ftp, mailto, https, urn, etc.
     Each one of those has a slightly different continuation, but all of them can be described in regexp expressions individually.

The two observations are not mutually exclusive.

**Comment by catull** [comment]
Since you want to support `uri`, the method name would be better named `parse_resource()`.

Either that or handle `uri` with a separate `parse_uri()`.

**Comment by larsga** [comment]
One option would definitely be to put this function in the experimental module. 

It is possible to do this with regexps, but it quickly gets messy.

One thing I'm seeing now is that this need shows up again in the Cxense pipeline, too. I think this is probably going to be a quite commonly needed function, so probably it's best to make this part of the core language.

**Comment by ecerulm** [comment]
I haven't write the doc for `parse-url` until I get the ok from @larsga about the output of `parse-url("https://www.aftonbladet.se/nyheter/a/opyK1R/snosmocka-pa-ingang--kan-bli-20-centimeter?utm_source=aaaa&utm_campaign=bbbb&utm_medium=cccc&utm_content=dddd&utm_term=eeee"`

should be:

```
   {
        "host": "www.aftonbladet.se",
        "parameters": {
          "utm_campaign": ["bbbb"],
          "utm_content": ["dddd"],
          "utm_medium": ["cccc"],
          "utm_source": ["aaaa"],
          "utm_term": ["eeee"]
        },
        "path": "/nyheter/a/opyK1R/snosmocka-pa-ingang--kan-bli-20-centimeter",
        "port": -1,
        "query": "utm_source=aaaa&utm_campaign=bbbb&utm_medium=cccc&utm_content=dddd&utm_term=eeee",
        "scheme": "https"
      } 
```

Note: 

*  `port` equals `-1` if the port is not specified (alternativelly it could be `null` instead). This is to match Java8 default behavior.
* `path` includes the leading `/` (I have seen similar functions in other languages where the starting slash is stripped). Current behaviour matches Java8 behaviour
* query parameters can be multivalued, that's why they are all arrays. For example `?utm_source=aa&utm_medium=bb&utm_source=cc` would result in `"parameters": {"utm_source": ["aa","cc"], "utm_medium": ["bb"]`

**Comment by larsga** [comment]
I think the output looks good, except the `port` thing. I think if it doesn't have a value we should just leave the entire key out.

I guess `http://example.org#foo` becomes the below?

```
{
        "host": "example.org",
        "path": "/",
        "fragment": "#foo",
        "scheme": "http"
} 
```

I guess we could have put this in the experimental module. What do you think?

@catull `parse-resource()` would be an incorrect name, because the resource is what the URI/URL refers to, and not the URI/URL itself. But it's true `parse-uri` is a more correct name if we support URNs, which I think we should. What do you think @ecerulm ?

**Comment by catull** [comment]
True, agree on the distinction between `resource` (as pointed to) vs. `uri` (address of a resource).

**Comment by ecerulm** [comment]
> I think the output looks good, except the port thing. I think if it doesn't have a value we should just leave the entire key out.

I can change that. `java.net.URL.getPort()` return -1 if no port is specified but I can detect this case. Same I guess with `path` because `URL.getPath()` will return a empty string `""` (not null) if no path is present in the url. 

I will add  a set of test cases for those cases (missing path, missing port, missing fragment, and so on) so that is more clear what is the expected output. 

> But it's true parse-uri is a more correct name if we support URNs,
Maybe it's better not to make statements about supporting URN or URIs in general. In this implementation I'm using `java.net.URL` which is really for URLs.
I guess you can try to parse `urn:isbn:0451450523` as a URL but really the best way would be to have a `parse-urn()` that splits that into `NSS`, `NID`, etc but I believe most languages settle for a parse url function and don't even try to provide a standard way to parse urn or uris in general. 
I really think we should implement just `parse-url` and explicitly support URL only.

**Comment by larsga** [comment]
Port, path, test cases: all good.

And I agree: let's do just `parse-url`. Those others are rare corner cases.

**Comment by ecerulm** [comment]
Ok, I've updated PR #110 with commit 44e0a993114ec51111205b52b4cfb7cb2cddf5e7, which takes care of empty object keys (`port`,`path`,`query`, `fragment` ) and adds documentation.
