### ISSUE TITLE
Update JSLT playground to 0.1.9

### ISSUE THREAD

**Issue by ecerulm** [schibsted/jslt#108]
the hash-int function is not available from the playground. I assume that the playground is running an old version of JSLT

**Comment by larsga** [comment]
Yeah, playground always runs latest released version. I'll update it once 0.1.9 is out, assuming my Schibsted AWS keys still work :-)

**Comment by ecerulm** [comment]
Any news on when the 0.1.9 can be released?

**Comment by larsga** [comment]
I'd like to get the #112 fix in and then do the release. I'm hoping I can do it today. If not it will be next week, probably toward the end of the week.

**Comment by catull** [comment]
I'd say the fix for #112 is to document that integer values MUST NOT have leading zeros.

**Comment by larsga** [comment]
0.1.9 is out now, and the playground updated.
