### ISSUE TITLE
min(), max() function is not available on JSLT demo playground web page

### ISSUE THREAD

**Issue by jungtaek-raphael** [schibsted/jslt#113]
min(), max() function is not available on JSLT demo playground web page

**Comment by larsga** [comment]
This is because the playground runs the latest released version, 0.1.8.

I will be releasing 0.1.9 as soon as I can. Things have been extremely hectic lately, but should calm down from next week onwards.

**Comment by larsga** [comment]
Playground demo is updated to 0.1.9 now.
