### ISSUE TITLE
Release with FileSystemResourceResolver?

### ISSUE THREAD

**Issue by ashauer** [schibsted/jslt#114]
Aloha!

We were very happy in our project to discover the `FileSystemResourceResolver` in the master branch. Can you give us an outlook when there will be a new release containing the resolver?

Thx-a-lot
Lutz

**Comment by larsga** [comment]
Sure, I'll add a comment here and close the ticket when the release is out. Shouldn't take long.

**Comment by larsga** [comment]
0.1.9 is released now and available from Maven Central.
