### ISSUE TITLE
Expressions with cyrillic symbols

### ISSUE THREAD

**Issue by 0ffer** [schibsted/jslt#115]
Hello!
Expressions with cyrillic letters do not parse.

For example next expression compilation
`
String transform = "{\"status\" : if (true) \"Отключен\" else \"Подключен\"}";
Parser.compileString(transform);
`
throws exception : `Parse error: Lexical error at line 2, column 25.  Encountered: "\u0420" (1056), after : "\""
com.schibsted.spt.data.jslt.JsltException: Parse error: Lexical error at line 2, column 25.  Encountered: "\u0420" (1056), after : "\""`

Is this the expected behavior?

**Comment by larsga** [comment]
This is definitely a bug, and an embarrassing one. Thank you for reporting! We'll fix this for the 0.1.9 release.

**Comment by larsga** [comment]
Fixed by commit cb80863

**Comment by 0ffer** [comment]
Thank you very much!
