### ISSUE TITLE
Library is thread safe

### ISSUE THREAD

**Issue by b0c1** [schibsted/jslt#119]
I want to use the library in a multi-threaded environment. It's thread safe when I compile the expression and multiple thread using same instance?

**Comment by larsga** [comment]
Yes, `Expression.apply` is thread-safe, except for the regular expression cache. Used by the regexp functions. I should fix that, really. Let me know if you think it might be an issue, and I will fix it.

**Comment by rjbordon** [comment]
Quick question here as I do not know exactly what the regex expression cache is and I'm using a custom function in a multi-threaded environment.

The custom function is responsible for injecting data to the outputted JSON which is not part of the original input JSON, the code is:

```java
public class InjectCustormerId implements Function {
   private final String customerId;
   
   public InjectCustormerId(final String customerId) {
      this.customerId = customerId;
   }

   @Override
   public String getName() {
     return "injectCustomerId";
   }
   ...
  @Override
  public JsonNode call(final JsonNode input, final JsonNode[] arguments) {
    return new TextNode(customerId);
  }
}
```

Then my JSLT expression looks like:
`{ "customerId": injectCustomerId(), "type": .type, ....}`

Finally, every thread will be creating a new InjectCustomerId, creates the Parser and apply it:

```java
final Collection<Function> functions = Collections.singleton(new InjectCustomerId(customer.getId()));
final Expression jsltExp = Parser.compileString(rule, functions);
final JsonNode output = jsltExp.apply(input);
```

Would be safe to use this function over this context? Can functions be messed up by threads and ending up injected data to the wrong input/output?

BTW, thank you for the great work on this lib!

**Comment by larsga** [comment]
The regexp cache was made thread-safe in commit 1d49175755b34aa0fe420df8c7495331c1f174e1, so that's not a worry any more. 

The function you're proposing is thread-safe if you create a separate `Expression` in each thread. It's not very efficient, though, because you have to parse the JSLT over again for every transform.

A better, and much simpler, solution would be to use a variable instead of a function, and to invoke it like this:

```
// do this somewhere else, and share expression across threads
Expression jsltExp = Parser.compileString(rule);

// then, in each thread:
Map<String, JsonNode> vars = Collections.singletonMap("customerId", new TextNode(customer.getId()));
JsonNode output = jsltExp.apply(vars, input);
```

I'm closing this issue now, because the library is thread-safe.

**Comment by rjbordon** [comment]
Thank you for the response @larsga.
