### ISSUE TITLE
Find a new home for JSLT playground.

### ISSUE THREAD

**Issue by mrange** [schibsted/jslt#121]
Hello Lars.

Due to internal organisation changes the bucket that is used by the JSLT playground falls under Adevinta ownership. Adevinta has asked us to find a new home for the JSLT playground as they plan to close this bucket and corresponding lambda. 

A new home is therefore needed for the playground.

What would be the best way to host the playground you think?

**Comment by larsga** [comment]
I'll contact you directly.

**Comment by larsga** [comment]
This has been solved now
