### ISSUE TITLE
Behavior of "fallback" function does not match documentation

### ISSUE THREAD

**Issue by fredriv** [schibsted/jslt#126]
The documentation at https://github.com/schibsted/jslt/blob/master/functions.md#fallbackarg1-arg2----value says that the `fallback` function should return the first value that evaluates to `true`, but instead it returns the first non-empty value (e.g. `false`, `0`, etc.).

Should replace the call to `NodeUtils.isValue` with `NodeUtils.isTrue` in the `Fallback` implementation? Or is the behavior intended and the docs need to be changed?

**Comment by larsga** [comment]
I think the behaviour is right, and it's the documentation that should change. We don't really care if the value is true or false. What we care about is having a value to return.

**Comment by ecerulm** [comment]
Is not this already closed by 5c32794023a51917df204a2696edaf8d27a75522?

**Comment by larsga** [comment]
It is, yes. I just forgot to close the issue. Thanks!
