### ISSUE TITLE
Summer holidays

### ISSUE THREAD

**Issue by larsga** [schibsted/jslt#13]
Just a quick notice to let everyone know that until August 13 I will mostly be on summer holidays. Replies will be slow until then.

**Comment by Deletz** [comment]
Welcome back from the holiday. 
Do you plan do make a new release with your new features?

Greetings

**Comment by larsga** [comment]
Thanks! 

Yes, I do, although I haven't decided on the timing yet. Are you waiting for some of the features? If so I can move it forward.

**Comment by Deletz** [comment]
Hey larsga,
yeah the flatten function and the filtering in arrays are the function which I looking forward to.

**Comment by vectro** [comment]
I'm waiting for these bugfixes to be released also, FWIW.

**Comment by larsga** [comment]
Doing the release now. Closing this ticket.
