### ISSUE TITLE
Get first occurance from array

### ISSUE THREAD

**Issue by ramsmcaodc** [schibsted/jslt#130]
Hi 

I have any array of an object and want to retrieve the first object based on the condition.

for example, below json may have more than one primary object inside Names. i want to retrieve firstname, lastname, middle name of the first PRIMARY record incase the names has PRIMARY element.

JSLT:
def checkPrimary(array) 
if(size($array)>0)
 [ 
 for ($array)
   if(.NameType == "PRIMARY") true else false
 ]
else
[false]

def getPrimaryFN(array) 
let names = if(size($array)>0)
 [ 
 for ($array)
    if(.NameType == "PRIMARY")  .FirstName else "" 
 ]
[join($names, "")]

def getPrimaryLN(array) 
let names = if(size($array)>0)
 [ 
 for ($array)
    if(.NameType == "PRIMARY")  .LastName else "" 
 ]
[join($names, "")]

def getPrimaryMN(array) 
let names = if(size($array)>0)
 [ 
 for ($array)
    if(.NameType == "PRIMARY")  .MiddleName else "" 
 ]
[join($names, "")]

def arrayOfStrings(array)
if(size($array)>0)
[for ($array) {"value" : .} ]
else
[{"value": null}]

def arrayOfObjects(array)
if(size($array)>0)
[ for($array) { "value": { for(.) .key: [{"value":.value}]}}]
else
[{"value":null}]

if(contains(true, checkPrimary(.attributes.names))) {
"type": "Type"
,"attributes": {
        "FirstName" : arrayOfStrings(getPrimaryFN(.attributes.names)),
        "MiddleName" : arrayOfStrings(getPrimaryMN(.attributes.names)),
        "LastName" : arrayOfStrings(getPrimaryLN(.attributes.names)),
	"Names" :arrayOfObjects(.attributes.names)
}
}else {

"type": "configuration/entityTypes/HCP"
,"attributes": {
	"Names" :arrayOfObjects(.attributes.names)

},
}

JSON:
{
	"attributes": {
		"names": [
			{
				"NameType": "PRIMARY",
				"FirstName": "ELI Test Fname",
				"MiddleName": "ELI Test Mname",
				"LastName": "ELI Test Lname",
				"SuffixName": "ELI Test Sfxname"
			},
{
				"NameType": "PRIMARY",
				"FirstName": "2nd priamryTest Fname",
				"MiddleName": "ELI Test Mname",
				"LastName": "ELI Test Lname",
				"SuffixName": "ELI Test Sfxname"
			}
		]
}
}

i was able to write the code but if i have more than 1 primary, then both primary names are coming in the output.

{
  "type" : "Type",
  "attributes" : {
    "FirstName" : [ {
      "value" : "ELI Test Fname2nd priamryTest Fname"
    } ],
    "MiddleName" : [ {
      "value" : "ELI Test MnameELI Test Mname"
    } ],
    "LastName" : [ {
      "value" : "ELI Test LnameELI Test Lname"
    } ],
    "Names" : [ {
      "value" : {
        "NameType" : [ {
          "value" : "PRIMARY"
        } ],
        "FirstName" : [ {
          "value" : "ELI Test Fname"
        } ],
        "MiddleName" : [ {
          "value" : "ELI Test Mname"
        } ],
        "LastName" : [ {
          "value" : "ELI Test Lname"
        } ],
        "SuffixName" : [ {
          "value" : "ELI Test Sfxname"
        } ]
      }
    }, {
      "value" : {
        "NameType" : [ {
          "value" : "PRIMARY"
        } ],
        "FirstName" : [ {
          "value" : "2nd priamryTest Fname"
        } ],
        "MiddleName" : [ {
          "value" : "ELI Test Mname"
        } ],
        "LastName" : [ {
          "value" : "ELI Test Lname"
        } ],
        "SuffixName" : [ {
          "value" : "ELI Test Sfxname"
        } ]
      }
    } ]
  }
}
please help me.

**Comment by larsga** [comment]
In the current version (0.1.9) the below will do it. It makes a slightly simpler JSON output than you need, but I think it's easy to see how to extend it. The idea is: just pick all primary names, then make the output from the first one.

```
let objects = [for (.attributes.names) . if (.NameType == "PRIMARY")]
{ 
  "FirstName" : $objects[0].FirstName,
  "MiddleName" : $objects[0].MiddleName,
  "LastName" : $objects[0].LastName
}
```

Just pick all the primary names, then transform the first one.

**Comment by larsga** [comment]
Can we close this now?

**Comment by ramsmcaodc** [comment]
yes pls
