### ISSUE TITLE
Injecting Configuration values on runtime to JSLT

### ISSUE THREAD

**Issue by prasannabalajims** [schibsted/jslt#131]
First of all, this is an amazing library with nailed down features and kudos to the team. I'm finding it difficult to understand how to pass configuration values in the runtime to JSLT from Java.

**Comment by larsga** [comment]
Could you give an example of the kind of configuration you have in mind?

**Comment by prasannabalajims** [comment]
I have an use case where I need to pass maxLength to a variable in the runtime that will be used for String slice in JSTL

**Comment by larsga** [comment]
What you can do is this:

```
Expression jslt = Parser. ... ;
JsonNode output = jslt.apply(
  Collections.singletonMap("maxLength", (JsonNode) new IntNode(Something.MAX_LENGTH)),
  input
);
```

then refer to `$maxLength` in the JSLT. The value will be whatever you pass in here.

Does that work?

**Comment by prasannabalajims** [comment]
This will work. Awesome!
Thanks for the prompt support
