### ISSUE TITLE
Is it possible to replace "(" with ""

### ISSUE THREAD

**Issue by prasannabalajims** [schibsted/jslt#132]
Getting ParseException while trying to replace parentheses .

**Comment by larsga** [comment]
I guess the problem here is that the second parameter (the matcher) is a regexp.

```
let input = "we have a (bad] parenthesis"
replace($input, "\\(", "[")
```
produces

```
"we have a [bad] parenthesis"
```

I see the error message you get is: `ERROR: java.util.regex.PatternSyntaxException: Unclosed group near index 1
(`

That should probably have been more helpful to the user.

**Comment by prasannabalajims** [comment]
Thank you. It helped and hence closing the issue
