### ISSUE TITLE
Accented characters not translating correctly when running from CLI and redirecting to a file on Windows

### ISSUE THREAD

**Issue by PS-davetemplin** [schibsted/jslt#138]
Input like "Très" becomes "Tr�s"...

INPUT
```
{"text": "Très"}
```

TRANSFORM
```
{"text": .text}
```

OUTPUT
```
{
  "text" : "Tr�s"
}
```

Or am I doing something wrong?

**Comment by larsga** [comment]
Where do you see this? What are you doing when it happens? Hard to answer before we know that, at least.

**Comment by PS-davetemplin** [comment]
Thanks for the quick reply! Turns out the problem I'm having [this problem](https://stackoverflow.com/questions/1259084/what-encoding-code-page-is-cmd-exe-using/17177904#17177904) when redirecting output from the command-line on Windows.

Incorrect result occurs when redirecting the output to a file like this...
```
java -cp jslt\build\libs\jslt-0.1.9-all.jar com.schibsted.spt.data.jslt.cli.JSLT TRANSFORM INPUT > OUTPUT
```
However, the correct result can be seen when outputting directly to the console like this...
```
java -cp jslt\build\libs\jslt-0.1.9-all.jar com.schibsted.spt.data.jslt.cli.JSLT TRANSFORM INPUT
```
So clearly not a jslt problem.

**Comment by catull** [comment]
Which encoding are your files ?
Assuming this is all-Windows, try calling the JVM with

```sh
java -Dfile.encoding=cp-1252 ......
```
or

```sh
java -Dfile.encoding=Windows-1252 .....
```

Does that help ?

**Comment by PS-davetemplin** [comment]
All files are UTF-8 encoded.

Adding the `-D` option does the trick...
```
java -Dfile.encoding=cp-1252 -cp jslt\build\libs\jslt-0.1.9-all.jar com.schibsted.spt.data.jslt.cli.JSLT TRANSFORM INPUT > OUTPUT
```

Thanks!

**Comment by larsga** [comment]
Thanks @catull for sorting this one out. :)
