### ISSUE TITLE
how can i implement  like   if(a==1 && b==2) ?

### ISSUE THREAD

**Issue by Boy2ang** [schibsted/jslt#139]
As the title shows

Is there any boss who can teach me ？

**Comment by larsga** [comment]
A bit hard to know exactly what you mean, but if you replace `&&` with `and` you might have what you're looking for.

**Comment by Boy2ang** [comment]
I see. Thank you very much!!

**Comment by larsga** [comment]
No problem. Closing the ticket, since it sounds like we solved your problem.
