### ISSUE TITLE
How to solve complex Nested Example

### ISSUE THREAD

**Issue by pratikpparikh** [schibsted/jslt#14]
@larsga and others,

I have following am struggling to flatten it, need help to understand what I am doing wrong.

Input
[
    {
        "movies": [
            {
                "movie": "The Equalizer II",
                "properties": {
                    "name": "action",
                    "creationDate": "2018-07-20T03:37:18.190909+00:00"
                }
            },
            {
                "movie": "Mamma mia",
                "properties": {
                    "name": "drama",
                    "creationDate": "2018-07-20T03:37:18.190909+00:00"
                }
            }
        ],
        "knownas": [
            {
                "movies": "release this week",
                "properties": {
                    "name": "premierlist",
                    "creationDate": "2018-07-20T03:37:18.190909+00:00"
                }
            }
        ],
        "top": {
            "properties": {
                "name": "new movies",
                "creationDate": "2018-07-20T03:37:18.190909+00:00"
            }
        }
    },
    {
        "movies": [
            {
                "movie": "Jurassic World: Fallen Kingdom",
                "properties": {
                    "name": "SiFi",
                    "creationDate": "2018-07-20T03:37:18.190909+00:00"
                }
            },
            {
                "movie": "incredibles 2",
                "properties": {
                    "name": "family",
                    "creationDate": "2018-07-20T03:37:18.190909+00:00"
                }
            }
        ],
        "knownas": [null],
        "top": {
            "properties": {
                "name": "monthly topper",
                "creationDate": "2018-07-20T03:37:18.190909+00:00"
            }
        }
    }
]

output:

[
    {
		"type": "monthly topper"
	},
	{
		"type" : "new movies"	  
	},
	{
		"type" : "premierlist"
	},
    {
		"name": "The Equalizer II"
		"type" : "action",
        "parents" : [{
			"type": "new movies"
		},{
			"type": "premierlist"
		}]
	},
	{
		"name": "Mamma mia"
		"type" : "drama",
        "parents" : [{
			"type": "new movies"
		},{
			"type": "premierlist"
		}]			  
	},
	{
		"name": "Jurassic World: Fallen Kingdom"
		"type" : "drama",
        "parents" : {
			"type": "monthly topper"
		}			  
	},
	{
		"name": "incredibles 2"
		"type" : "drama",
        "parents" : {
			"type": "monthly topper"
		}			  
	}
]

currently, I have the following transformation

[for (.[0:]) {"type": .top.properties.name},
[for (.movies){
  "name": .movie,
  "type": .properties.name
}]
]

**Comment by larsga** [comment]
I looked at this a bit, but I can't really understand the logic of the transform you're trying to implement. To be honest I think you should reconsider whether you really want to create output that looks like this.

But if you really want to do this, can you explain the logic behind the output? I tried to work it out, but failed.

**Comment by pratikpparikh** [comment]
@larsga this was a made-up scenario (as I can't disclose my real scenario), but let me try to explain this little better, we usually run into many scenarios where hierarchical data needs to flattened to support simple data objects on the user interface side. The use case arises when we have a social networking site, data analytics aggregation, etc...  Currently, the limitation that is seen is that for every array loop we need [for (single node not nested){}] and you can't aggregate this up.  Hope this helps, thank you for helping me on your holiday's

**Comment by larsga** [comment]
I don't really understand what you mean by making `[]` optional.

> Currently, the limitation that is seen is that for every array loop we need [for (single node not nested){}] and you can't aggregate this up

I don't understand what you mean by this, either. "Single node not nested"? What does that mean?

You can certainly address as deeply as you want into the input object with `.foo.bar.baz` etc. And the object you retrieve can have any shape you want.

> and you can't aggregate this up.

I don't understand this, either. If you have two for loops you can concatenate the results by doing

    [for (...) ...] + [for (...) ...]

It would be much easier to help you if you could be more concrete, for example by showing an example that I can understand. I'm pretty sure it should be possible to do what you want, but since I don't know _what_ you want, it gets difficult.

**Comment by pratikpparikh** [comment]
Here is a another similar example:
Input 
`{
   "readers":[
      {
         "merchantID":3,
         "id":20,
         "merchant":"Location 1",
         "label":"A179207",
         "state":"ACTIVE",
         "timestampLastActivity":1424176492950,
         "details":[
            {
               "readerTypeName":"myReader",
               "id104":"ID104",
               "id106":"ID106",
               "configName":"MyConfiguration",
               "firmwareVersion":"00.09.53-6319",
               "timestamp":1424176492947
            }
         ]
      },
      {
         "merchantID":3,
         "id":446,
         "merchant":"Location 1",
         "label":"A123091",
         "state":"ACTIVE",
         "timestampLastActivity":1424178336044,
         "details":[
            {
               "readerTypeName":"myReader",
               "id104":"ID104_01",
               "id106":"XY-0091",
               "configName":"My Configuration 02",
               "firmwareVersion":"00.09.53-6319",
               "timestamp":1424178320164
            },
            {
               "readerTypeName":"myReader",
               "id104":"ID104_02",
               "id106":"XY-0015",
               "configName":"My Configuration 01",
               "firmwareVersion":"00.09.53-6319",
               "timestamp":1424178335614
            }
         ]
      }
   ]
}`

Output should be
`[
    {
         "merchantID":3,
         "id":20,
         "merchant":"Location 1",
         "label":"MIC179207",
         "state":"ACTIVE",
         "timestampLastActivity":1424176492950,
         "readerTypeName":"myReader",
         "id104":"ID104",
         "id106":"ID106",
         "configName":"MyConfiguration",
         "firmwareVersion":"00.09.53-6319",
         "timestamp":1424176492947
    },
    {
         "merchantID":3,
         "id":446,
         "merchant":"Location 1",
         "label":"MIC123091",
         "state":"ACTIVE",
         "timestampLastActivity":1424178336044,
         "readerTypeName":"myReader",
         "id104":"ID104_01",
         "id106":"XY-0091",
         "configName":"My Configuration 02",
         "firmwareVersion":"00.09.53-6319",
         "timestamp":1424178320164
    },
    {
         "merchantID":3,
         "id":446,
         "merchant":"Location 1",
         "label":"MIC123091",
         "state":"ACTIVE",
         "timestampLastActivity":1424178336044,
         "readerTypeName":"myReader",
         "id104":"ID104_02",
         "id106":"XY-0015",
         "configName":"My Configuration 01",
         "firmwareVersion":"00.09.53-6319",
         "timestamp":1424178335614
    }
]`

Transformation requires me to loop thru readers and its details.  So I am flattening this to details merged with readers details.  So the logical step for me is to try the following:
`[for (.readers[0:].details[0:]) {
  
}]`
but i get null back, shouldn't it give me `[{},{},{}]`

**Comment by larsga** [comment]
Now I understand. Thank you! This was interesting, and a new kind of transform I haven't seen before. I agree that this should be possible, and in fact it is, even if a little awkward:

```
def flatten(arrayofarrays)
  if ($arrayofarrays)
    $arrayofarrays[0] + flatten($arrayofarrays[1 : ])
  else
    []

flatten([for (.readers)
  let parent = (.)
  [for (.details)
    . + {for ($parent) .key : if (.key != "details") .value}]
])
```

Let me walk you through the logic here. The core of this solution is:

```
[for (.readers)
  let parent = (.)
  [for (.details) . + $parent]
]
```

For every object inside `.readers.details` this will produce the union of that object and its parent. Unfortunately, this duplicates the `details` key, and it's a nested array.

The first problem is solved (somewhat awkwardly) with the `{for ... }` loop. The second one, even more awkwardly, by defining a `flatten` function to flatten the nested array into a single array.

**Comment by larsga** [comment]
I would be happier if there were a built-in `flatten` and the `{for ...}` supported an `if`. Then we could write the solution as:

```
flatten([for (.readers)
  let parent = (.)
  [for (.details) . + {for ($parent) .key : .value if (.key != "details")}]
])
```

**Comment by pratikpparikh** [comment]
@larsga I think that would be good and thank you for your help on this.  I will update you as I test out other examples.

**Comment by pratikpparikh** [comment]
@larsga I think we look good with your suggested solution and approach, adding flatten as a native function would make this work.  Can we do that as part of this issue? or do you need a new issue?

**Comment by larsga** [comment]
I can do it as part of this issue, but note that you don't actually need `flatten` to be built in. The example code works as given.

**Comment by pratikpparikh** [comment]
I am aware, but there is value in having it built in.  So that users don't have to carry (DRY) this in their reusable jslt.  Does that make sense?

**Comment by larsga** [comment]
I agree completely. I just wanted to make it clear that you don't have to wait for it to be built in, just in case.

**Comment by pratikpparikh** [comment]
@larsga I am all set for this use case.

**Comment by pratikpparikh** [comment]
@larsga I have another unique problem in dealing with nested structures and need your opinion.  I have duplicate reference node, i need to figure out how to private the duplicate from being created.  I started building a global array, and thinking that i need check that array in flatten to remove duplicates.  If you can give it a look and let me know what you think best option here is then it will be great.  Below is current input, expected output and current template.

Input

> [
>     {
>         "chapters": [
>             {
>                 "name": "a-f"
>             },
>             {
>                 "name": "b"
>             }
>         ]
>     },
>     {
>         "chapters": [
>             {
>                 "name": "a-f"
>             },
>             {
>                 "name": "e"
>             }
>         ]
>     },
>     {
>         "chapters": [
>             {
>                 "name": "l-p"
>             },
>             {
>                 "name": "m"
>             }
>         ]
>     },
>     {
>         "chapters": [
>             {
>                 "name": "v-z"
>             },
>             {
>                 "name": "v"
>             }
>         ]
>     },
>     {
>         "chapters": [
>             {
>                 "name": "v-z"
>             },
>             {
>                 "name": "z"
>             }
>         ]
>     }
> ]
> 

Expected Output
> [
>   {
>     "name": "a-f"
>   },
>   {
>     "name": "b",
>     "parents": [
>       {
>         "name": "a-f"
>       }
>     ]
>   },
>   {
>     "name": "e",
>     "parents": [
>       {
>         "name": "a-f"
>       }
>     ]
>   },
>   {
>     "name": "l-p"
>   },
>   {
>     "name": "m",
>     "parents": [
>       {
>         "name": "l-p"
>       }
>     ]
>   },
>   {
>     "name": "v-z"
>   },
>   {
>     "name": "v",
>     "parents": [
>       {
>         "name": "v-z"
>       }
>     ]
>   },
>   {
>     "name": "z",
>     "parents": [
>       {
>         "name": "v-z"
>       }
>     ]
>   }
> ]

Current Template

> def flatten(arrayofarrays)
>    if ($arrayofarrays)
>      $arrayofarrays[0] + flatten($arrayofarrays[1 : ])
>    else
>      []
> 
> let globalTopNodeCache = [for (.) if(.chapters and size(.chapters) > 0) .chapters[0].name]
> 
> flatten([for (.)
> let chapterZero = if(.chapters and size(.chapters) > 0) .chapters[0] else ""
> [{"name" : $chapterZero .name}] + [for (.chapters[1 : ]) {"parents":[{"name":$chapterZero .name}],"name" : .name}]
> ])

**Comment by larsga** [comment]
Could we do a new issues for this? I have a kind of solution for it, but would like to separate the issues.

**Comment by pratikpparikh** [comment]
@larsga done. #16

**Comment by larsga** [comment]
Commit cacd465 implements `flatten()`

**Comment by pratikpparikh** [comment]
@larsga tested and looks good. Thank you.
