### ISSUE TITLE
Import Resolver Interface

### ISSUE THREAD

**Issue by wdonne** [schibsted/jslt#140]
Currently imports can only be resolved through the class path. This is difficult for integrations. A simple solution is to add an import resolver interface to the parser to which physical imports are delegated. This is reminiscent of how XML parsers work.

**Comment by larsga** [comment]
There is `ResourceResolver` you can pass to the `Parser` to do control how imports are resolved: https://javadoc.io/static/com.schibsted.spt.data/jslt/0.1.10/com/schibsted/spt/data/jslt/Parser.html#withResourceResolver-com.schibsted.spt.data.jslt.ResourceResolver-

There is even a resolver for the file system: https://javadoc.io/static/com.schibsted.spt.data/jslt/0.1.10/com/schibsted/spt/data/jslt/impl/FileSystemResourceResolver.html

It sounds like this provides what you need?

**Comment by wdonne** [comment]
Absolutely! I should have looked better. Sorry for that. Thanks!

**Comment by larsga** [comment]
No worries 👍
