### ISSUE TITLE
Filter array 

### ISSUE THREAD

**Issue by Boy2ang** [schibsted/jslt#142]
source ==>

"info":[
             {"age":"18","name":"bob"},
             {"age":"50","name":"jack"}
]

-------------------------------
target ==>

info2: [for(.info)

  // todo :  i want to get item where name > 20 , what shoud i do , Can someone help me ?
  {
     "age2" : .age,
    "name2" : .name
  }

]
---------------------------------
Desired outcome

"info2":[
             {"age":"50","name":"jack"}
]

**Comment by larsga** [comment]
Can't you just do like this?

```
{"info2" : [for(.info) . if (number(.age) > 20]}
```

**Comment by Boy2ang** [comment]
Thank you for helping me in time. I am using a translation, but I may not express it accurately enough. If this is the case, how can I achieve it?
----------------------------------------------
source ==>

"info_a:{"age":"18","name":"bob"},
"info_b":{"age":null,"name":"bob"}

--------------------------------------------
target ==>

info2: [
   {
       "age2" : info_a.age,
       "name2" : info_a.name
   },
  // todo : If .age  is null, the node is removed
   {
       "age2" : info_b.age,
       "name2" : info_b.name
   }
]
---------------------------------------------
Desired outcome

"info2":[
{"age":"18","name":"bob"}
]

**Comment by larsga** [comment]
Just change the `if` to `if (number(.age) > 20 or not(.age))`?

**Comment by Boy2ang** [comment]
info2: [
{
"age2" : info_a.age,
"name2" : info_a.name
},
// todo : If .age is null, the node is removed  (Can expressions be supported here? Can you share the complete example? Thank you very much)
{
"age2" : info_b.age,
"name2" : info_b.name
}
]

**Comment by larsga** [comment]
I'm sorry, but I don't really understand what you are trying to do, or what the question is.

**Comment by Boy2ang** [comment]
I want to merge several nodes into an array, but I need to select what I need when Merging

**Comment by Boy2ang** [comment]
But I don't know how to write my judgments in this format
---------------------------------------------------------------
info2: [
{
"age2" : info_a.age,
"name2" : info_a.name
},
 if (number(info_b.age !=null) //  This will report syntax errors
{
"age2" : info_b.age,
"name2" : info_b.name
}
]

**Comment by larsga** [comment]
You need to write `.info_b` to make it select the `info_b` key. So `if (.info_b.age !=null)`.

**Comment by Boy2ang** [comment]
Thank you very much. That's what I want to say.

**Comment by larsga** [comment]
Good. Can we close this ticket?

**Comment by Boy2ang** [comment]
I'm sorry for missing a point in my example, but I reported syntax errors even when I used the template before. Did You update it later?

**Comment by Boy2ang** [comment]
Maybe I was careless before, thank you very much, ha ha ha
