### ISSUE TITLE
Constructing JSON key identifier from a variable

### ISSUE THREAD

**Issue by prasannabalajims** [schibsted/jslt#144]
Hi,

We are having a scenario where the JSON keys will be constructed dynamically based on the Input. It will be based on the index of the element in an array. Is there a way we can set the key accordingly? 

Here is the sample below.
Input JSON : 

{
  "products": [
    {
      "name": "Laptop",
      "cost": "1200"
    },
    {
      "name": "Phone",
      "cost": "700"
    }
  ]
}

Expected Output

{
  "products": {
    "product1": "Laptop",
    "product2": "Phone"
  }
}

**Comment by wdonne** [comment]
Perhaps this would work:

```
def set-key(object, key, value)
  $object + {for ([$key]) . : $value}
```

**Comment by larsga** [comment]
Issue #56 will let you compute keys dynamically. I'm working on that one at the moment. However, you probably don't need that one, because object comprehensions already have dynamic keys.

Issue #127 lets you iterate over an array with an index. Once that one's done you can solve this with:

```
{
  "products": {
    for (zip-with-index(.products)) 
    "product" + .index : .value.name 
  }
}
```

**Comment by prasannabalajims** [comment]
@larsga Thanks for the input. Found a workaround and will wait for the zip-with-index function.
