### ISSUE TITLE
Add value inside array

### ISSUE THREAD

**Issue by althaf0416** [schibsted/jslt#147]
My input json is 

{
	"attributes": {
		"identifiers": [
			{
				"Type": "NAME",
				"ID": "11111"
			},
			{
				"Type": "address",
				"ID": "23456"
			}
		]
	},
	"crosswalks": {
		"value": "1234567",
		"source": "hadoop"
	}
}

and i need output to be printed as

{
  "attributes" : {
    "Identifiers" : [ {
      "value" : {
        "Type" : [ {
          "value" : "NAME"
        } ],
        "ID" : [ {
          "value" : "11111"
        } ]
      }
    }, {
      "value" : {
        "Type" : [ {
          "value" : "address"
        } ],
        "ID" : [ {
          "value" : "23456"
        } ]
      }
    }, {
      "value" : {
        "Type" : [ {
          "value" : "hadoop"
        } ],
        "ID" : [ {
          "value" : "1234567"
        } ]
      }
    } ]
  }
}

i tried to iterate identifier and derive the output, but i also need crosswalk within the identifier array

**Comment by larsga** [comment]
Can't you add the two arrays together? Like this?

```
{
   "attributes" : {
      "Identifiers" : [for (.attributes.identifiers)
        {"Type" : [{"value" : .Type}],
         "ID"   : [{"value" : .ID}]}        
      ]
      +
      [
        {"Type" : [{"value" : .crosswalks.source}],
         "ID"   : [{"value" : .crosswalks.value}]} 
      ]
   }
}
```

**Comment by catull** [comment]
It is difficult to read it.
Use the formatting, to make it look like

```json
{
  "attributes": {
    "identifiers": [
      {
        "Type": "NAME",
        "ID": "11111"
      },
      {
        "Type": "address",
        "ID": "23456"
      }
    ]
  },
  "crosswalks": {
    "value": "1234567",
    "source": "hadoop"
  }
}
```

And the output is

```json
{
  "attributes": {
    "Identifiers": [
      {
        "value": {
          "Type": [
            {
              "value": "NAME"
            }
          ],
          "ID": [
            {
              "value": "11111"
            }
          ]
        }
      },
      {
        "value": {
          "Type": [
            {
              "value": "address"
            }
          ],
          "ID": [
            {
              "value": "23456"
            }
          ]
        }
      },
      {
        "value": {
          "Type": [
            {
              "value": "hadoop"
            }
          ],
          "ID": [
            {
              "value": "1234567"
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by althaf0416** [comment]
Kindly find my JSLT mapping file where i was able to iterate identifier alone,

def arrayOfObjects(array)
if(size($array)>0)
[for($array) {"value": {for(.) .key: [{"value": if(.value=="") null else .value}]}}]
else
[{"value":null}]



{
    "attributes": {
	"Identifiers" :arrayOfObjects(.attributes.identifiers)
}
}

**Comment by althaf0416** [comment]
@larsga Thanks it works for me

**Comment by althaf0416** [comment]
Closing the issue

**Comment by catull** [comment]
Here's an alternative:

```python
def arrayOfObjects (array)
  [ for ($array) { "value": { for(.) .key: [ { "value": .value }] } }]

def convertCrossWalks (walks)
    [{
        "Type": $walks.source,
        "ID"  : $walks.value
    }]

{
  "attributes": {
    "Identifiers": arrayOfObjects (
       .attributes.identifiers +
        convertCrossWalks (.crosswalks) )
  }
}
```
