### ISSUE TITLE
How does one replaces the dot operation with a custom one?

### ISSUE THREAD

**Issue by davidginzbourg** [schibsted/jslt#149]
I'm using Clojure and I'm trying to integrate this library with a service of mine. It's pretty common to use "keywords" in Clojure as hashmap keys instead of String. Is there a way to change the dot operation to make JSLT use those keywords for dict access instead of strings?

Thank you.

**Comment by larsga** [comment]
The input to JSLT is Jackson `JsonNode` object, so the question doesn't seem to apply at all. Or do I misunderstand what you mean?

**Comment by davidginzbourg** [comment]
You're completely right, it doesn't apply here at all. Thank you!
