### ISSUE TITLE
Big decimal number is represented in scientific notation

### ISSUE THREAD

**Issue by hli-nw** [schibsted/jslt#156]
I have a Json object like {"amount": 3000000.01}, when that passes through JSLT with transformation of { * : . }, the result is {"amont": 3.0E6}. What I expected is {"amount": 3000000.01}.

Is this because the NumericOperator only support LongNode and DoubleNode? Could you please add support for DecimalNode so that I can see big decimal?

**Comment by larsga** [comment]
I don't think this has anything to do with JSLT. Most likely the problem is that Jackson is serializing `3000000.01` as `3.0E6`. In other words, if you just loaded the JSON with Jackson, then wrote it back to a string/file, you'd very likely see the same thing.

**Comment by hli-nw** [comment]
Thanks a lot for the quick response! I think you have a point that Jackson itself has its peculiar way in terms of precision and scientific notation. But JSLT also converts to scientific notation, or maybe since JSLT uses Jackson as the engine, the conversion is beyond JSLT's control? 

public class JSLTTest
{
    @Test
    public void testBigDecimal()
    {
        JsltConverter jsltConvert = new JsltConverter();

        BigDecimalTest testAmount = new BigDecimalTest(new BigDecimal(30000000.001));
        JsonObject testJson = JsonObject.mapFrom(testAmount);

        System.out.println("from json - " + testJson.toString());
        System.out.println("from jslt - " + jsltConvert.convert(testJson.toString()));
        System.out.println("---\n");

        testAmount = new BigDecimalTest(new BigDecimal(300000000000000000000.01));
        testJson = JsonObject.mapFrom(testAmount);

        System.out.println("from json - " + testJson.toString());
        System.out.println("from jslt - " + jsltConvert.convert(testJson.toString()));
        System.out.println("---\n");

        JsonObject rawJson = new JsonObject("{\"amount\":300000000000000000000.01}");

        System.out.println("from json - " + rawJson.toString());
        System.out.println("from jslt - " + jsltConvert.convert(rawJson.toString()));
        System.out.println("---\n");
    }

    class BigDecimalTest
    {
        @JsonProperty("amount")
        private BigDecimal amount;

        BigDecimalTest(BigDecimal val)
        {
            amount = val;
        }
    }

    class JsltConverter
    {
        private ObjectMapper d_mapper = new ObjectMapper();
        {
            d_mapper.registerModule(new ParameterNamesModule())
                    .registerModule(new Jdk8Module())
                    .registerModule(new JavaTimeModule());
        }

        private Expression d_expression = Parser.compileString("{ * : . }");

        public String convert(String jsonStr)
        {
            try
            {
                JsonNode eelNode = d_mapper.readTree(jsonStr);
                JsonNode protoNode = d_expression.apply(eelNode);

                return d_mapper.writeValueAsString(protoNode);
            }
            catch (Exception e)
            {
                e.printStackTrace();

                return null;
            }
        }
    }

}


from json - {"amount":30000000.0009999983012676239013671875}
from jslt - {"amount":3.0000000001E7}
--- JSLT converts to scientific notation

from json - {"amount":300000000000000000000}
from jslt - {"amount":300000000000000000000}
---

from json - {"amount":3.0E20}
from jslt - {"amount":3.0E20}
---

**Comment by catull** [comment]
The import statements in the class are very important here.

**Comment by hli-nw** [comment]
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;
import com.schibsted.spt.data.jslt.Expression;
import com.schibsted.spt.data.jslt.Parser;
import io.vertx.core.json.JsonObject;
import org.junit.Test;

import java.math.BigDecimal;

**Comment by larsga** [comment]
There are two problems with your test:
1. It obscures what the input is, so you don't really know what you're testing.
2. I've claimed the problem is in `writeValueAsString`, but only the JSLT part of your test goes through that method.

When I rewrite the test so it actually passes everything through `writeValueAsString` we get this output:

```
from json - {"amount":30000000.0009999983012676239013671875}
from jslt - {"amount":30000000.0009999983012676239013671875}
---

from json - {"amount":300000000000000000000}
from jslt - {"amount":300000000000000000000}
---

from json - {"amount":3.0E20}
from jslt - {"amount":3.0E20}
---
```

It's clear that the problem is not JSLT.

This is the code:

```
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.DecimalNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
// import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
// import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
// import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;
import com.schibsted.spt.data.jslt.Expression;
import com.schibsted.spt.data.jslt.Parser;

import java.math.BigDecimal;
import java.io.IOException;

public class JSLTTest
{
  public static void main(String[] argv) throws IOException {
    JsonNode testJson = makeJson(new BigDecimal(30000000.001));
    doTest(testJson);

    testJson = makeJson(new BigDecimal(300000000000000000000.01));
    doTest(testJson);

    String rawJson = "{\"amount\":300000000000000000000.01}";
    doTest(parse(rawJson));
  }

  private static void doTest(JsonNode input) throws IOException {
    System.out.println("from json - " + serialize(input));
    System.out.println("from jslt - " + serialize(convert(input)));
    System.out.println("---\n");
  }

  private static JsonNode makeJson(BigDecimal amount) {
    ObjectNode obj = d_mapper.createObjectNode();
    obj.put("amount", new DecimalNode(amount));
    return obj;
  }

  private static ObjectMapper d_mapper = new ObjectMapper();
  // static {
  //   d_mapper.registerModule(new ParameterNamesModule())
  //     .registerModule(new Jdk8Module())
  //     .registerModule(new JavaTimeModule());
  // }

  private static Expression d_expression = Parser.compileString("{ * : . }");

  public static JsonNode parse(String json) throws IOException {
    return d_mapper.readTree(json);
  }

  public static JsonNode convert(JsonNode input) {
    return d_expression.apply(input);
  }

  public static String serialize(JsonNode node) throws IOException {
    return d_mapper.writeValueAsString(node);
  }
}
```

**Comment by hli-nw** [comment]
Thanks a lot for the prompt and detailed response! Since we're using Vert.x as the main library, it complicates things more. I've come up with a workaround. 

I'm glad that we picked JSLT. Thanks again for your help!
