### ISSUE TITLE
Incrementing an int variable in array

### ISSUE THREAD

**Issue by sampleuser4** [schibsted/jslt#157]
Hi ,
 I have an array rows=[ "test","test1", "test3","test"]
I want to increment an int variable while interating array like

let cnt = 0
[for($rows) cnt++]
$cnt

I am getting errors in this format. Is there any other way?

**Comment by larsga** [comment]
You can't modify the value of variables in JSLT -- it's a functional language.

Perhaps if you can explain what you're trying to do we can suggest another way to do it?

**Comment by up-to-you** [comment]
`let arr = ["1", "2", "3"]
 { "field": sum([for ($arr) number(.)]) }`

`{
  "field" : 6
}`

maybe some simple sum() func is sufficient enough ?

**Comment by larsga** [comment]
If we take the example literally 

```
let rows=[ "test","test1", "test3","test"]
size($rows)
```

would do it, but I assume that's not what they were actually looking for.
