### ISSUE TITLE
Using previous-sibling (XSLT feature)

### ISSUE THREAD

**Issue by mohitsingh0610** [schibsted/jslt#173]
Is the a way to write transform a json based on the attribute of sibling in a jsonnode. Eg.

{
  "docNum": "123",
  "doclines": [
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test1"
      }
    },
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test1"
      }
    },
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test2"
      }
    },
    {
      "docNum": "123",{
  "docNum": "123",
  "doclines": [
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test1"
      }
    },
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test1"
      }
    },
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test2"
      }
    },
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test3"
      }
    }
  ]
}
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test3"
      }
    }
  ]
}

TO

{
  "docNum": "123",
  "doclines": [
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test1"
      }
    },
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test1"
      }
    },
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test2"
      }
    },
    {
      "docNum": "123",
      "docDetails":"test"
      "cdoclines": {
        "actualdocNum": "Test3"
      }
    }
  ]
}

The transform json contains node only if actualdocNum is unique.

**Comment by larsga** [comment]
I think maybe the best way is to use the group-by function: https://github.com/schibsted/jslt/blob/master/docs/experimental.md

Group on `actualdocNum`, then for each key, check how many objects are grouped under it. If 1, it's unique.

I'd write you an example, but your input JSON is so broken that I gave up trying to fix it.

**Comment by mohitsingh0610** [comment]
Thanks @larsga . It worked.
