### ISSUE TITLE
Feature required for getting parameters from the parser and using it in jslt files

### ISSUE THREAD

**Issue by mejuhi** [schibsted/jslt#177]
Enhancement: Need new feature in which we are able to supply list of parameters to the jslt file for transformation. For now we can only use values either from input payload or by creating a variable in jslt file, would also like to access values passed in run time environment. 

For example equivalent feature in xsl 3 is explained [here](https://www.w3schools.com/xml/ref_xsl_el_with-param.asp)

**Comment by larsga** [comment]
This is already supported. In the API you can pass parameters to the `Expression` and those will be visible as variables inside the JSLT transform.

**Comment by mejuhi** [comment]
Not sure then if i am doing the right way, but i am not able to see any method accessed from my `template` to pass the parameter
```
Expression template = new Parser(new FileReader(new File(transformationMapping))).withResourceResolver(new FileSystemResourceResolver()).compile(); 
JsonNode transformed_data = template.apply(input_json);
```
It would be a great help if you can help me with this

**Comment by larsga** [comment]
It's the second `apply` method [here](https://javadoc.io/static/com.schibsted.spt.data/jslt/0.1.11/com/schibsted/spt/data/jslt/Expression.html). The "variables" are your parameters.

**Comment by mejuhi** [comment]
Ahh, sorry! I was looking it all wrong!! My bad, Thanks a lot! I will try this one out :)

**Comment by larsga** [comment]
No worries. :)

Please close the issue if/when it works.

**Comment by mejuhi** [comment]
Yes, i tried and tested it out, I was able to send parameter and access it in jslt file
Thankyou! :)
