### ISSUE TITLE
Static code analysis support

### ISSUE THREAD

**Issue by danigiri** [schibsted/jslt#192]
**Problem description**
People can write valid JSLT code that contains incorrect regular expressions. The code parses correctly but fails at runtime. The failure can be deterministic (regexp as a standalone expression) or indeterministic (regepx is part of an OR boolean clause that is triggered only under certain conditions).

The Java Pattern [compile](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#compile(java.lang.String)) set of methods will throw a [PatternSyntaxException](https://docs.oracle.com/javase/7/docs/api/java/util/regex/PatternSyntaxException.html) when the expression is compiled.

The static helper method `getRegexp` will be called in [BuiltinFunctions](https://github.com/schibsted/jslt/blob/master/core/src/main/java/com/schibsted/spt/data/jslt/impl/BuiltinFunctions.java) at runtime, which means people may write JSLT that compiles and they expect to be valid but fails under some circumstances (or always if on a standalone expression).

**Expected behaviour**
Incorrect regexp patterns in functions like `test` fail at JSLT parsing time, surfacing the issue raised by the underlying regexp runtime, as that is independent from the input and can potentially be known at compile time. This behaviour is expected even when regexp expressions are nested within boolean expressions.

**Actual behaviour**
Parsing does not fail, running the JSLT fails at runtime when the right boolean expression is triggered or all the time when the expression is standalone.

**Workarounds**
Partial: `Expression` public interface returned by the public API `Parser` allows you to call `apply`. You could build a tester that parses any JSLT input code and runs it on an static JSON input, say an empty JSON doc. This would deterministically catch invalid regexes that are standalone and not part of a nested boolean.

Complete: To catch nested regexes in nested booleans, there would need to be a test document in sync with the JSLT code that triggers all the necessary boolean expressions and checks the regexp. This is equivalent to writing comprehensive unit tests for all JSLT code.

Complete: use static analysis techniques, obtain the JSLT Abstract Syntax Tree (AST), do a search for `test` and other regexp using expression nodes, check the regexp correctness (check them against an empty JSON doc). This is a deterministic method that catches all invalid regexes.

`Expression` public interface returned by the public API `Parser` does not expose useful methods to implement this, like getting children expressions and the name of the functions. It can be fairly trivially implemented by using internal interfaces `ExpressionImpl`, which works but is very brittle as is not using public contracts.

Complete: extending `Expression` to return children expression and the name/type of the expression. Exposing the name is not mandatory but means the testing can be done only on relevant nodes and not have to brute force test all JSLT code expressions to look for `PatternSyntaxException`s which is computationally expensive. Once that interface is exposed, it is fairly trivial to implement static code analysis like testing regexes, and may be useful for other use-cases.

**Comment by larsga** [comment]
This is a good point. It's a side-effect of how we chose to optimize use of regular expressions, but it's definitely a negative side-effect, since it makes error detection harder for users.

It should be pretty easy to fix, so we should be able to close this quite quickly.

My proposed fix is simply to make sure we compile any regular expressions passed to the functions as literals during the compile phase. We can add test cases for this, too.

**Comment by danigiri** [comment]
cc @rodrigo-molina

**Comment by larsga** [comment]
Fixed

**Comment by danigiri** [comment]
Thank you very much, we will test it but looking at the PR and tests I would not expect any problems 😄

**Comment by larsga** [comment]
Let me know if you need a release. I was planning to not do any more releases on this branch, and instead release 0.2 with no Jackson.

**Comment by rodrigo-molina** [comment]
hi @larsga 
if you can create the release with this fix we could upgrade the version in our components 😀

Moving to `0.2` won't be straight away for us - we'll need to double check the impact since we depend on jslt everywhere.

**Comment by larsga** [comment]
I'll make a release, but it may take a few days.

Regarding 0.2 it would be great if you could assess the impact and post to discussion #185. It's useful to know how a change like that impacts major users.

**Comment by rodrigo-molina** [comment]
thanks 🙏

I'll add a task to our backlog to do so.
