### ISSUE TITLE
problem loading a jstl file - Parse error: Can't compare null and 2 at C:\\specs.jstl:7:1

### ISSUE THREAD

**Issue by pratikpparikh** [schibsted/jslt#2]
@larsga as a first example I have following in my template.  When I test it with http://spt-data-dev-public-web.s3-website-eu-west-1.amazonaws.com/jstl2.html everything works but when I call with Parser.compile with string reader and it fails with an exception "Can't compare null and 2 at C:\\specs.jstl:7:1".  The problem it seems is that parentSize is not getting evaluated?

JSTL
let parentSize = size(.parents)
if ($parentSize == 1)  
{
  "size":"Single"
  
}
else if ($parentSize >= 2)
{
  "size": "many"
}
else 
{
  "size": "0"
}

Input
{
  "name": "park",
  "parents": [
      "home",
      "land",
      "public"
  ]
}

**Comment by pratikpparikh** [comment]
Input mismatch with let statement.

**Comment by larsga** [comment]
Glad to see you sorted it out. Note that it's easier to write it this way:

```
let parentSize = size(.parents)
{
  "size": if ($parentSize == 1)
      "Single"
    else if ($parentSize >= 2)
      "many"
    else
      "0"
}
```

**Comment by pratikpparikh** [comment]
@larsga does it do the null check automagically if .parents are not present?

**Comment by larsga** [comment]
Yes, it does. If `parents` is missing then: `size(.parents) => size(null) => null`
