### ISSUE TITLE
Need support for converting epoch timestamp to UTC at MILLIsecond level

### ISSUE THREAD

**Issue by dipankardevops** [schibsted/jslt#202]
Currently format-time() function doesn't support converting timestamp to current time with millisecond level time. Any workaround available for this ?

**Comment by larsga** [comment]
Why do you say it's not supported? It works for me:

`format-time(1529677391.321, "yyyy-MM-dd'T'HH:mm:ss.SSS")`

**Comment by dipankardevops** [comment]
Thanks, its resolved.
