### ISSUE TITLE
Attributes based on condition

### ISSUE THREAD

**Issue by althaf0416** [schibsted/jslt#204]
My input is 

"attributes": {
    "names": [
      {
        "FirstName": "HOPE",
        "NameType": "PRIMARY",
        "LastName": "GRIFFIN",
        "MiddleName": "THOMAS"
      }
    ]
}

and my mapping is 

def arrayOfStrings(array)
if(size($array)>0)
[for($array) {"value" : if(.!="") string(.) else null}]
else
[{"value": null}]

let objects = [for (.attributes.names) . if (uppercase(.NameType) == "PRIMARY")]

"attributes": {
	"FirstName" :arrayOfStrings([$objects[0].FirstName])
	,"MiddleName" :arrayOfStrings([$objects[0].MiddleName])
	,"LastName" :arrayOfStrings([$objects[0].LastName])

if lenght of MiddleName is greater than 1, i have to have the below output

"attributes" : {
    "FirstName" : [ {
      "value" : "HOPE"
    } ],
    "MiddleName" : [ {
      "value" : "THOMAS"
    } ],
    "LastName" : [ {
      "value" : "GRIFFIN"
    } ]

if MiddleName is equal to 1 my output will be 

"attributes" : {
    "FirstName" : [ {
      "value" : "HOPE"
    } ],
    "LastName" : [ {
      "value" : "GRIFFIN"
    } ]

Kindly help me in formatting the mapping

**Comment by larsga** [comment]
Wouldn't this do it?

```
,"MiddleName" : if (size($objects[0].MiddleName) > 1)    
    arrayOfStrings([$objects[0].MiddleName])
```

**Comment by althaf0416** [comment]
I should not get "MiddleName" itsself

**Comment by althaf0416** [comment]
The Solution works, thanks for your support

**Comment by althaf0416** [comment]
is it possible to get the first letter of a string?
