### ISSUE TITLE
Substring of a String

### ISSUE THREAD

**Issue by althaf0416** [schibsted/jslt#206]
Is it possible to get the first character of a string id string size is less than 1

Mapping file is 

def arrayOfStrings(array)
if(size($array)>0)
[for($array) {"value" : if(.!="") string(.) else null}]
else
[{"value": null}]

let objects = [for (.attributes.names) . if (uppercase(.NameType) == "PRIMARY")]

"attributes": {
	"FirstName" :arrayOfStrings([$objects[0].FirstName])
       ,"MiddleName" : if (size($objects[0].MiddleName) > 1) 
arrayOfStrings([$objects[0].MiddleName])[0 : 1]
 else  arrayOfStrings([$objects[0].MiddleName])
,"LastName" :arrayOfStrings([$objects[0].LastName])

For input, 

"attributes": {
    "names": [
      {
        "FirstName": "HOPE",
        "NameType": "PRIMARY",
        "LastName": "GRIFFIN",
        "MiddleName": "Ured"
      }
    ]}

**Comment by larsga** [comment]
Something like this?

```
let str = "foo"
if (size($str) >= 1) $str[0] else ""
```

**Comment by althaf0416** [comment]
Thanks for your valuable time, it works
