### ISSUE TITLE
Are there any way to filter out nulls from result?

### ISSUE THREAD

**Issue by shark300** [schibsted/jslt#208]
Hello, 
I have the following JSLT file:

```
{
  "formId": "Company",
  "fieldValues":
    [
        {
            "name": "CompanyName",
            "value": {
                "en_US": string(.data.companyName)
            }
        },
        if (contains("Android", array(.data.platforms)))
        {
            "name": "PlatformAndroid",
            "value": {
                "en_US": true
            }
        },
        if (contains("IOS", array(.data.platforms)))
        {
            "name": "PlatformIOS",
            "value": {
                "en_US": true
            }
        },
        if (contains("MicrosoftStore", array(.data.platforms)))
        {
            "name": "PlatformMicrosoftStore",
            "value": {
                "en_US": true
            }
        },
        {
            "name": "Pack",
            "value": {
                "en_US": string(.data.pack)
            }
        }
    ]
}
```

But the fieldValues array contains nulls if there are no platforms checked because of the behavior of if statement.

Before this solution, I tried to iterate over .data.platforms but I couldn't because in this case the result will be a separated array.
After that I tried to define a new function for that, but I couldn't.

Do you have any idea? Thank you.

**Comment by larsga** [comment]
I don't actually understand what the problem is. Can you give an example?

**Comment by shark300** [comment]
Hi @larsga 
Thank you for your reply.
I would like to tranform this JSON:

```json
{
  "data": {
    "companyName": "dummyCompanyName",
    "platforms": [
       "MicrosoftStore"
    ],
   "pack": "dummyPack"
  }
}
```

to this JSON:

```json
{
  "formId": "Company",
  "fieldValues":
    [
        {
            "name": "CompanyName",
            "value": {
                "en_US": "dummyCompanyName"
            }
        },
        {
            "name": "PlatformMicrosoftStore",
            "value": {
                "en_US": true
            }
        },
        {
            "name": "Pack",
            "value": {
                "en_US": "dummyPack"
            }
        }
    ]
}
```

but my JSLT configuration transform it to this format with additional null values:

```json
{
  "formId": "Company",
  "fieldValues":
    [
        {
            "name": "CompanyName",
            "value": {
                "en_US": "dummyCompanyName"
            }
        },
        null,
        null,
        {
            "name": "PlatformMicrosoftStore",
            "value": {
                "en_US": true
            }
        },
        {
            "name": "Pack",
            "value": {
                "en_US": "dummyPack"
            }
        }
    ]
}
```

So to recap, I would like to filter out/prevent this additional null values.

**Comment by catull** [comment]
Hmm, can you share your JSTL code ?

**Comment by shark300** [comment]
Yes, sure.

```
{
  "formId": "Company",
  "fieldValues":
    [
        {
            "name": "CompanyName",
            "value": {
                "en_US": string(.data.companyName)
            }
        },
        if (contains("Android", array(.data.platforms)))
        {
            "name": "PlatformAndroid",
            "value": {
                "en_US": true
            }
        },
        if (contains("IOS", array(.data.platforms)))
        {
            "name": "PlatformIOS",
            "value": {
                "en_US": true
            }
        },
        if (contains("MicrosoftStore", array(.data.platforms)))
        {
            "name": "PlatformMicrosoftStore",
            "value": {
                "en_US": true
            }
        },
        {
            "name": "Pack",
            "value": {
                "en_US": string(.data.pack)
            }
        }
    ]
}
```

**Comment by contatolucascosta** [comment]
Hi @shark300 

Follow the solution.
Basically you transform all content in a array, then you print (with loop "for") the elements != null

Jslt:

{
  "formId": "Company",
  "fieldValues": [for(array(
    [
        {
            "name": "CompanyName",
            "value": {
                "en_US": string(.data.companyName)
            }
        },
        if (contains("Android", array(.data.platforms)))
        {
            "name": "PlatformAndroid",
            "value": {
                "en_US": true
            }
        },
        if (contains("IOS", array(.data.platforms)))
        {
            "name": "PlatformIOS",
            "value": {
                "en_US": true
            }
        },
        if (contains("MicrosoftStore", array(.data.platforms)))
        {
            "name": "PlatformMicrosoftStore",
            "value": {
                "en_US": true
            }
        },
        {
            "name": "Pack",
            "value": {
                "en_US": string(.data.pack)
            }
        }
    ]
    )). if( . != null)]
}

**Comment by catull** [comment]
Here's a different approach, using function and decomposition:

```json
let platformMap = {
  "Android"       : "PlatformAndroid",
  "IOS"           : "PlatformIOS",
  "MicrosoftStore": "PlatformMicrosoftStore"
}

def processPlatforms (platforms)
  [ for ($platforms)
        {
            "name": get-key ($platformMap, .),
            "value": {
                "en_US": true
            }
        }
  ]

{
  "formId": "Company",
  "fieldValues": [
        {
            "name": "CompanyName",
            "value": {
                "en_US": .data.companyName
            }
        },
        {
            "name": "Pack",
            "value": {
                "en_US": .data.pack
            }
        }
    ] + processPlatforms (.data.platforms)
}
```

It would support payloads such as:

```json
{
  "data": {
    "companyName": "dummyCompanyName",
    "platforms": [
       "Android",
       "IOS",
       "MicrosoftStore"
    ],
   "pack": "dummyPack"
  }
}
```

**Comment by catull** [comment]
The problem with this pattern

```
if (contains("PPP", array(.data.platforms))) {
    "name": "PlatformPPP",
    "value": {
        "en_US": true
    }
},
```
is that JSLT always produces a node, either `null` or `{ "name": "PlatformPPP" ... }`.

The trick is to collect the constant values (`Android`, `IOS` and `MicrosoftStore`, as well their platform values) into a map.
The map completely removes the repetition of `if (condition) { node-instructions }`.

Also, you do not have to use the invasive ". if (. != null)" at the end.

There can be tag values for which `null` is an acceptable value.
That if-filter removes all null-values.

**Comment by shark300** [comment]
Thank you Guys, you are great! I'm testing all approaches as well.

**Comment by catull** [comment]
If any "environment" E leads to "Platform${E}", you can actually short-cut it to

```
{
  "formId": "Company",
  "fieldValues": [
        {
            "name": "CompanyName",
            "value": {
                "en_US": .data.companyName
            }
        },
        {
            "name": "Pack",
            "value": {
                "en_US": .data.pack
            }
        }
    ] + [ for (.data.platforms) {
            "name": "Platform" + .,
            "value": {
                "en_US": true
            }
        }
    ]
}
```

It would be capable of processing this payload:

```json
{
  "data": {
    "companyName": "dummyCompanyName",
    "platforms": [
       "Android",
       "Blackberry",
       "IOS",
       "MicrosoftStore",
       "Raspberry"
    ],
   "pack": "dummyPack"
  }
}
```

**Comment by shark300** [comment]
I have another idea, probably we can generate platform names from incomming values (I have to discuss with the business about that):

```
def processPlatforms (platforms)
  [ for ($platforms)
        {
            "name": "Platform" + .,
            "value": {
                "en_US": true
            }
        }
  ]

{
  "formId": "Company",
  "fieldValues": [
        {
            "name": "CompanyName",
            "value": {
                "en_US": .data.companyName
            }
        },
        {
            "name": "Pack",
            "value": {
                "en_US": .data.pack
            }
        }
    ] + processPlatforms (.data.platforms)
}

```

**Comment by larsga** [comment]
Thanks for taking care of this one, @catull. Much appreciated. :)

**Comment by catull** [comment]
@shark300 It is a balance between correctness and openness.

The map approach is for correctness, it only processes accepted values.

The latter one, which you also detected, would allow un-intended values, like "ReallyOffensiveEnvironment" or the likes.

**Comment by shark300** [comment]
@catull 
Yes, I agree with you. However, I have to respect the opinion of business guys. :)

**Comment by catull** [comment]
True, they know what they want, you implement it.

**Comment by catull** [comment]
By the way, do you know why you have to add the `fieldValues` and the result of `processPlatforms` ?

Watch what happens if you replace that "+" with ", " ;-)
This was my first attempt.

**Comment by shark300** [comment]
Legacy reason. :)
We would like to replace an old Liferay form export with a new microservice based solution but we have to keep backward compatiblity for specified fields. Fortunately, we could skip A LOT OF junk of Liferay internal form's representations :)
