### ISSUE TITLE
How to use "*:." in a function?

### ISSUE THREAD

**Issue by ca7erina** [schibsted/jslt#21]
I have input json like this one : 
```
{
  "A": "CH802053",
  "B": [],
  "C": [
    {
      "D": "F10",
      "E": [
        {
          "id": 1,
          "name": "xx"
        },
        {
          "id": 2,
          "name": "xxx"
        }
      ],
     "F": "asef",
     "G": "xwrew",
     "H": "123"
    }
  ]
}
```
I have JSLT .
```
def func1(CObject) {
	"E": [
		for ($CObject.E) size(.)
	]
	// how to keep rest object value here : "D","F","G","H"
	//*:.
}

{
	"C": [ for (.C) func1(.)],
	*: .
}
```

The result is 
```
{
  "C" : [ {
    "E" : [ 2, 2 ]
  } ],
  "A" : "CH802053",
  "B" : [ ]
}

```

My question is how can I keep the value of "D","F","G","H" in the "func1", The expression "* : . " give me null pointer here.

**Comment by larsga** [comment]
You can do this another way, by using the `+` operator to combine objects. The left-hand side wins. So you can write your function like this:

```
def func1(CObject) {
	"E": [
		for ($CObject.E) size(.)
	]
} + $CObject
```

That will overwrite the `"E"`, but keep the rest.

**Comment by ca7erina** [comment]
Thanks very much, it works pretty well !

**Comment by larsga** [comment]
Excellent. I'll close this ticket, then. :)
