### ISSUE TITLE
Can I import a A.jslt from B.jslt, when  A.jslt also import B.jslt ? 

### ISSUE THREAD

**Issue by Psycokwet** [schibsted/jslt#238]
Hello,

I'm not sure if that an issue or deliberate, but, I have those three files : 

main.jslt (entry point)
````javascript
import "a.jslt" as a
import "b.jslt" as b

let a_result= a:get()
let a_result = b:get()

$a_result+$a_result
````

a.jslt
````javascript
import "b.jslt" as b

def get()
  {"a":"a"}
````

b.jslt
````javascript
import "a.jslt" as a

def get()
  {"b":"b"}
````

I get 
````javascript
{
  "status": "INTERNAL_SERVER_ERROR",
  "status_code": 500,
  "timestamp": "04-11-2021 03:06:32",
  "message": "JSON transformation error",
  "debug_message": "Module 'a.jslt' is already imported at b.jslt:2:1"
}
````

And I wonder if that a wanted mecanism or not. Since I would need to do some recursives calls using this logic.

Thank you for your time !

**Comment by larsga** [comment]
Yes, this is deliberate, to avoid infinite import loops, and also to avoid cyclical dependencies.

**Comment by Psycokwet** [comment]
Ok ! Thank you for the clarification :) That what I was thinking, but needed to be sure.
