### ISSUE TITLE
Question about deal with two kinds input Json at once.

### ISSUE THREAD

**Issue by ca7erina** [schibsted/jslt#24]
I have 2 kinds of json input:

sometimes it is
```
{
  "A" :{
   "B":"33",
   "C":[]
  }
}
```
sometimes changes to this
```
{
  "A" :{
   "B":[],
   "C":"33"
  }
}
```

Currently, I have two JSLT, to deal with two kinds of input.
one is

```
{
  "A" : {
    "B":.A.B+"x"
  }
}
```
the other is 
```
{
  "A" : {
    "C":.A.C+"x"
  }
}
```

My Question is: Is it possible do some check in the JSLT to deal with two kinds of input at one JSLT ?

**Comment by larsga** [comment]
Something like this?

```
{
  "A" : if (is-array(.A.B)) {
    "C":.A.C+"x"
  } else {
    "B":.A.B+"x"
  }
}
```

**Comment by larsga** [comment]
You're welcome. :)
