### ISSUE TITLE
Iterate through 2 arrays at the same time

### ISSUE THREAD

**Issue by Psycokwet** [schibsted/jslt#243]
Hello !
I have
````jslt
let array1 = [
  {...},
  {...}
]

let array2 = [
  {...},
  {...}
]
````
I need to have access at array1[0] when i'm treating array2[0], as well, as array1[1] when i'm treating array2[1] and so on, I need to iterate in both of them as the same rythm, supposing then that they have the same size.

I don't see how I can progress in both of them at the same time with JSLT, is there something that I am missing ?

Thank you for reading !

Best regards

**Comment by larsga** [comment]
You can do `zip($array1, $array2)` and loop over the result. That should give you what you want.

**Comment by Psycokwet** [comment]
Hmm, thank you, I completely passed over that function !
I'll try that :)

**Comment by Psycokwet** [comment]
Arf, I just realized the version of jslt that we use is before zip... Is there any workaround I could use instead of zip? Updating the version we use is out of the question for the moment being unfortunately...

**Comment by Psycokwet** [comment]
Hello ! I did find a solution ! So I'm sharing it here for other who may pass by here :) 
Thank you @larsga  for your range function, I just had to use another function with it for it to work, but, it helps a lot !

````python
def int-value(v)
  let unpadded = capture($v, "0+(?<n>\\d+)")
  number(get-key($unpadded, "n", $v), 0)

def range(n)
  if (int-value($n) < 0)
    []
  else if (int-value($n) == 0)
    [0]
  else
    range(int-value($n) - 1) + [$n]


let indices_array = range(size($array1) - 1)

def iterate_through_both() 
  [
    for ($indices_array )
      do_stuff_on_both($array1[.], $array2[.])
  ]
````

**Comment by larsga** [comment]
Yeah, this will work, but your `int-value()` function is really strange. Why do you need it? `size()` will give you an integer, so I don't understand the point of it.

**Comment by Psycokwet** [comment]
I'm not sure why I need it, and  I may be overusing it, but without it, I was getting errors in my range function. Keep in mind that I'm using an outdated version of jslt, so, I do have some weird issues because of that.
It's not the only weird workaround that we have to not update our JLST version haha...

**Comment by larsga** [comment]
I tried with this definition and it worked fine for me. I bet you don't need it.

```
def int-value(v)
  $v
```

**Comment by Psycokwet** [comment]
Well, I don't know why I was getting errors yesterday then. I tried again without it, and so far so good. I didn't change anything in this function, so I guess I did something wrong while using it before. Thank you for your input :)
