### ISSUE TITLE
Referencing a node outside of an array element being looped

### ISSUE THREAD

**Issue by balagueri21** [schibsted/jslt#247]
Here's a sample JSON structure.
```
{
	"employeeDetails":  {
		"firstName": "John",
		"lastName": "Doe",
		"hireDate": "2022-01-01"
	},
	"documents": [
		{
			"documentId" : "12345"
			"documentName" : "My Document"
			"validityDate" : "2022-06-07"
		}
	]
}

```
Now, I want to loop inside the documents array using this:

```
[for(.documents)
...
]
```

Within the for loop, I can only reference elements relative to the current array element. For example, I can access `documentId`, `documentName` and `validityDate` using the dot access (.) inside the loop.

However, what I want to achieve within my loop, is to have a reference to an element outside of the current array element. For example, I want to access `.employeeDetails.hireDate` inside my loop. Is this possible? A sample use case is like I want to do some comparison between `.employeeDetails.hireDate` and `.validityDate` of each document in the documents array.

One way I thought that would work, is capture the outside element into a variable and reference later inside my loop.
For example:
```
let hireDate = .employeeDetails.hireDate
[for(.documents)
...
//do comparisons here between $hireDate and .validityDate
...
]
```

Question: Are there other ways to do this without a variable declaration?

**Comment by larsga** [comment]
Binding a variable is the only way to do this at present. It would be possible to add some syntax you could use to reference the input object directly, but in this case I think a variable is probably the best solution.
