### ISSUE TITLE
Bad implementation of Max(arg1, arg2) function?

### ISSUE THREAD

**Issue by SirSerch** [schibsted/jslt#250]
Hi! In our project we are working with JSLT and found a very curious case when we use the max function with numbers as Strings. 

If you use max function with the Strings "10" and "2" the function returns "2". As We see this is a bad implementation but not of the Max function but from String.compareTo functions. 

Because they return the difference between the characters of the smallest string. 

In this case, the funtion return "2" because is greater than "1", but we think the Max function should return "10" because is larger than "2" omiting the integer value.

What do you think?

**Comment by catull** [comment]
The behaviour is correct IMHO.

If you compare strings, the comparison is done lexicographically.
The first character is the deciding factor, "2" >= "1".

Why does the max function need to know if the strings can be interpreted as numeric values ?
If you want to compare numeric values, you have to convert the two strings to integers first, and then call max on those converted values.

**Comment by larsga** [comment]
I completely agree with @catull.

`"10" < "2"` returns `true`, just as it should, because lexicographically the first string sorts before the second. As he says, whether these strings can be interpreted as numbers is irrelevant.

**Comment by SirSerch** [comment]
Good morning guys, you are right. A misunderstanding on my part. Thanks for the reply and sorry for the issue. Best regards!
