### ISSUE TITLE
Throwing cutom exception with message in jslt

### ISSUE THREAD

**Issue by jugup** [schibsted/jslt#260]
Hello! was trying to create a jslt where a parameter against some if conditions, if we dont find any match it should throw an exception and stop processing jslt any further, and java code where we trigger the transformation should throw an exception with same message

Find the sample jslt function used 
```
def convertVolumedimension, value) {
  if (uppercase($dimension) = "MTQ")
    $value * 1000
  else if (uppercase($dimension) = "DMQ")
    $value
  else if (uppercase($dimension) = "CMQ")
    $value * 0.001
  else if (uppercase($dimension) = "MMQ")
    $value * 0.000001
  else
    ////THROW AN EXCPTION SAYING THAT $dimension DOES NOT MATCH ANY CASES
}
```

just wondering how should this part look like to achive this
```
  else
    ////THROW AN EXCPTION SAYING THAT $dimension DOES NOT MATCH ANY CASES
```

Would really appreciate some help on this

**Comment by larsga** [comment]
You could use `error(string($dimension) + " does not match any cases")`
