### ISSUE TITLE
Determine index of current item in object array

### ISSUE THREAD

**Issue by ronMilne** [schibsted/jslt#271]
Given the following Json
```
{
  "Addresses": [
    {
      "type": "RegisteredOfficeAddress",
      "addressCategoryType": "G",
      "addressTypeCode": 162
    },
    {
      "type": "PlaceOfBusiness",
      "addressCategoryType": "G",
      "addressTypeCode": 164
    },
    {
      "type": "EmailAddress",
      "addressCategoryType": "E",
      "addressTypeCode": 170
    },
    {
      "type": "MobileAddress",
      "addressCategoryType": "T",
      "addressTypeCode": 122,
      "latestInd": 1
    }
  ]
}
```

I need to add latestInd when I'm processing the final object in the array; is there a way to determine what index is currently being processed? so in essence "lastestInd": if( islastelement) ?? I'm iterating over the array using a [For] construct

Ron.

**Comment by larsga** [comment]
You can use `zip-with-index` to get an array where each element of the array appears together with its index number. You can then compare the index number to the length of the entire array.

**Comment by ronMilne** [comment]
Yep works - thanks. Just out of curiosity could you not make .key the index when iterating over a collection? I must admit .key I do find frustrating but that's another question.

**Comment by larsga** [comment]
What's the problem with `.key`?
