### ISSUE TITLE
I want to call external java method in jslt during transformation, is it possible???

### ISSUE THREAD

**Issue by vermaamrita** [schibsted/jslt#278]
Example 
input json
{
 "abc":"abc"
}

output
{
"abc": this value should come from a java method call
}

Then how do we write the jslt rule.

**Comment by vermaamrita** [comment]
@larsga , can you explain it, better if with an small example

**Comment by larsga** [comment]
[This documentation](https://github.com/schibsted/jslt/blob/master/extensions.md) should have what you need.
