### ISSUE TITLE
How to set counter value after each iteration of for loop in jslt

### ISSUE THREAD

**Issue by joel19913** [schibsted/jslt#281]

**Comment by larsga** [comment]
JSLT is a functional language, meaning it has no variables. So you can't change the value of variables. However, I'm sure it can do what you want anyway.

What's the goal? To have an index number inside the loop, or to count something to use that count after the loop?

**Comment by joel19913** [comment]
The goal is to count the occurence of the value . suppose if I have an array of values [ b, a, b, b ].
 if the value is b then I have to set it as b1 and similarly the 3 element of array is b, but it is the second occurence of value b so, I need to set it as b2, so on.

**Comment by larsga** [comment]
Do you want the number 3, or do you want each element numbered inside the array?

**Comment by joel19913** [comment]
I want the occurence of element. If value is b and it is first occurence in array then I have to set some field value  as b1, if value b is second occurence of the array then b2, and if value b is third occurence the b3 . Eventually I have to count the occurence and append the occurence count along with the value.

**Comment by larsga** [comment]
Taking this as input

```
[{"v":"b"}, {"v":"a"}, {"v":"b"}, {"v":"b"}]
```

this JSLT

```
def countBs(array)
  size([for ($array) . if (.v == "b")])

let array = (.)
[for (zip-with-index(.))
  if (.value.v == "b")
    .value + {"field" : "b" + countBs($array[ : .index + 1])}
  else
    .value
]
```

produces this output:

```
[ {
  "field" : "b1",
  "v" : "b"
}, {
  "v" : "a"
}, {
  "field" : "b2",
  "v" : "b"
}, {
  "field" : "b3",
  "v" : "b"
} ]
```

The downside is that performance is O(n^2).

**Comment by joel19913** [comment]
That's great. Thank you!
