### ISSUE TITLE
How to round off value to 2 digit precision. Eg 55.0000 to 55.00

### ISSUE THREAD

**Issue by joel19913** [schibsted/jslt#286]

**Comment by larsga** [comment]
Your example is not rounding, because the two numbers are equal. Are you asking how to display it in a string with two decimals after the period?

**Comment by larsga** [comment]
Do you understand the question?

**Comment by joel19913** [comment]
Yes I understand. I don't want to round off the value. I have a value like 40.0000 I wanted to trim it upto 2 digits after period. I. e  40.00

**Comment by larsga** [comment]
This question is a bit frustrating, because I've had it before, but I've never been able to fully figure out what it is people are asking for.

Sometimes they may actually want rounding, like [here](https://github.com/schibsted/jslt/discussions/237). Or maybe not. It's hard to tell.

[This guy](https://github.com/schibsted/jslt/issues/73), I think, wanted the number formatted inside a string in a particular way.

Although you don't say so, I suspect it's the formatting inside a string that you want, too. Am I right?

**Comment by joel19913** [comment]
Yes I referred above two examples. but I don't get the solution.I don't want the round off, instead I wanted to format value upto 2 digits after the period.

**Comment by joel19913** [comment]
Is there a solution for this issue? All i want is to format the value to have two digits after the decimal.

**Comment by catull** [comment]
It depends what you want to achieve.

If it is being processed elsewhere, then "55.0", "55.00" and "55" are all the same value.

But do you display it on an UI ?

Now, knowing almost nothing about your requirements, here is an attempt.

Take this input:

```json
{
  "values": [
    55,
    55.0,
    55.00,
    39.585,
    13.995,
    53.7745
  ]
}
```

with this transformation:

```python
def formatNumberTotwoDecimals (num)
  let fix      = floor ($num)
  let partial  = floor (100 * ($num - $fix))
  let dezi     = floor ($partial / 10)
  let centi    = mod ($partial, 10)
  let afterDot = join ([$dezi, $centi], "")
  join ([$fix, $afterDot], ".")

{
  "values": [
    for (.values)
      formatNumberTotwoDecimals (.)
  ]
}
```

you obtain:

```json
{
  "values" : [ "55.00", "55.00", "55.00", "39.58", "13.99", "53.77" ]
}
```

Is this what you want ?

**Comment by catull** [comment]
Hang on, I made a mistake.

Here is a more precise version of the transformation.

```python
def formatNumberTotwoDecimals (num)
  let fix      = floor ($num)
  let partial  = floor (100 * ($num - $fix))
  let dezi     = floor ($partial / 10)
  let centi    = mod ($partial, 10)
  let afterDot = join ([$dezi, $centi], "")
  join ([$fix, $afterDot], ".")

{
  "values": [
    for (.values)
      formatNumberTotwoDecimals (. + 0.005)
  ]
}
```

With input:

```json
{
  "values": [
    55,
    39.585,
    13.995,
    53.7745
  ]
}
```

the result would be:

```json
{
  "values" : [ "55.00", "39.59", "14.00", "53.77" ]
}
```

Hope this helps.
