### ISSUE TITLE
jq walk - traverse json and apply function

### ISSUE THREAD

**Issue by joaopastor** [schibsted/jslt#299]
hey there,
I am looking to visit all nodes and apply a function.
the desired behaviour is the same as **jq's walk**.
My goal is to the following:

```
jq 'walk(
      if type == "string" then
          # Remove non printable characters [\u0000-\u001F\u007F-\u009F]
          gsub("[\u0000-\u001F\u007F-\u009F]"; "") |
          # Replace curly quotes with straight quotes
          gsub("“|”"; "\u201C") |
          gsub("`|’"; "\u0027") |
          gsub("\\\""; "")
      else
          .
      end
  )'
```

the `gsub` could be achieved as an extended function where a `replaceAll`  was used.
but as for the **walk** part goes, I am not seeing any other alternative rather than coding a recursive traverse function.
Is there something in place?

Thanks for all the support given so far, very much appreciated.

**Comment by larsga** [comment]
There's no alternative at present to the recursive function, unfortunately.

**Comment by joaopastor** [comment]
oh that's a pity.
I'll try to code some recursive traversal.
Anyhow, it's a must I'd say. XSLT had it.
Again, thanks so much for the provided support so far

**Comment by larsga** [comment]
It's something it would be nice to have, but it's non-trivial to integrate, particularly as there's a number of different designs that could be chosen.

**Comment by joaopastor** [comment]
I'll just replace them special chars in the java side of things. easier.
thanks
