### ISSUE TITLE
Add option to preserve objects order

### ISSUE THREAD

**Issue by pirafrank** [schibsted/jslt#3]
Even if the JSON standard defines list of objects as unordered (http://www.rfc-editor.org/rfc/rfc7159.txt) add option to preserve objects order to maintain output JSON readability

**Comment by larsga** [comment]
JSLT returns a `JsonNode`, and looking at the implementation of that it seems the order of the keys is the insertion order. So it may be possible to do this, but the question is: what do you want the order to be? Can you give an example?

**Comment by tonysparks** [comment]
Unless I'm mistaken -- this expression:

```
let t = {"one":"1","two": "3", "three": "3" } {for ($t) .key : .}
```

should return:
```
{"one":{"key":"one","value":"1"},"two":{"key":"two","value":"3"},"three":{"key":"three","value":"3"}}
```
But instead returns:
```
{"three":{"key":"three","value":"3"},"two":{"key":"two","value":"3"},"one":{"key":"one","value":"1"}}
```

**Comment by larsga** [comment]
You're right. In fact, it's worse than that, because

```{"one":"1","two": "3", "three": "3" }```

returns

```{
  "three" : "3",
  "two" : "3",
  "one" : "1"
}```

Which is kind of nuts.

This looks like it's worth fixing, yes.

**Comment by larsga** [comment]
Commit 37f00c6e183d1985f1da6a3628ee91e606aa8663 solves the problem that object literals have their keys consistently reversed. Now when I try my example above, or yours with the `let`, the order of the keys is preserved.

If I let `{"one":"1","two": "3", "three": "3" }` be the input and run `{for (.) .key : .}` I get:

```
{
  "one" : {
    "key" : "one",
    "value" : "1"
  },
  "two" : {
    "key" : "two",
    "value" : "3"
  },
  "three" : {
    "key" : "three",
    "value" : "3"
  }
}
```

I don't know if this gives @pirafrank what he wants, but at least the behaviour makes a lot more sense now.
