### ISSUE TITLE
Upgrade Demo playground: is-decimal() function is not there

### ISSUE THREAD

**Issue by ecerulm** [schibsted/jslt#30]
When I run `is-decimal(1.0)` I get 

    ERROR: com.schibsted.spt.data.jslt.JsltException: No such function: 'is-decimal' at <inline>:1:1

I suppose that the Demo playground is running an old version of the `jstl` library missing the commit dac7b386775060b30610e9a13c0b537144d952f7

**Comment by larsga** [comment]
Yes. Usually I only upgrade the playground when we release a new version. I should do it now, but in a rush to travel.

**Comment by esthernwogu** [comment]
I am facing the same issue, except I am running version `0.1.3`, which is the latest version according to
https://search.maven.org/ and the readme

**Comment by larsga** [comment]
Ok. I'm on the road, but I'll release 0.1.4 on Monday.

**Comment by larsga** [comment]
0.1.4 is released, and the demo playground is updated now.
