### ISSUE TITLE
Workaround to include null values when no API access?

### ISSUE THREAD

**Issue by nickdos** [schibsted/jslt#308]
I've read the [docs that explain](https://github.com/schibsted/jslt/blob/master/docs/api.md#object-key-filter) how to set the filter option to include null values in the output. However, that does not help in my case of using the Apache Nifi [JSLTTransformJSON processor](https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-jslt-nar/1.22.0/org.apache.nifi.processors.jslt.JSLTTransformJSON/index.html), as there is no access to modify the API, as it's already compiled. I could build a custom processor myself but before I commit to this, I thought I'd check here first.

I'm trying to filter out key/values that contain a key that starts with "ignored" (e.g. keys are ignored1, ignored2... ignored16). I want to preserve null value elements, as it makes life easier in my Nifi pipeline when using the "infer schema" option.

Input JSON:
```json
{
  "ignored1" : "one",
  "ignored2" : "two",
  "ignored3" : null,
  "foo" : "something",
  "bar" : "ok",
  "bash" : null
}
```
desired output:
```json
{
  "foo" : "something",
  "bar" : "ok",
  "bash" : null
}
```

This works:
```json
{
  * - ignored1, ignored2, ignored3 : .
}
```

But I have to know how many instances of each "ignored_N_" fields exist. This could get larger than intended over time, due to changes in input data source. And I'm unclear why it does respect null values.

This works without hardcoding every key but omits null values:
```json
{
    for (.) .key: .value 
    if (not(contains("ignored", .key)))
}
```

Is there another way I haven't thought of?

Ideally, if the `* - foo` syntax could support regex or wildcards, this would solve my problem.

**Comment by larsga** [comment]
Unfortunately for you, the fact that `* - foo` works is a bug in JSLT, so extending the syntax will not give you the hoped-for results. (Thanks for reporting the bug! I'll be fixing that.)

What you need is for Nifi to give you access to the filter option through a new property (it's possible to use JSLT for the filter). Presumably this is something you could add yourself? It shouldn't be hard.

Either that, or to modify the Nifi default to basically accept all values. Presumably this will leave other users unhappy.

**Comment by nickdos** [comment]
Thanks for confirming my fears 😉 and those are good suggestions.

I might be able to get away with removing the null values after all, as my initial testing had issues that I think were unrelated to the null values. There is also the JoltTransformJSON processor but I prefer the JSLT syntax.
