### ISSUE TITLE
Parser error when adding a new row after else statement

### ISSUE THREAD

**Issue by moienGoli** [schibsted/jslt#309]
I am using the JSLT Playground. This piece of code works perfectly 
```
if (.id) {
  "myId" : .id,
} else {
  "myId" : 404,
  "message" : "Missing Id"
}
```

But when I am adding another row I am getting an exception from Parser. I am wondering if I am doing something wrong here 🤔  ?

```
if (.id) {
  "myId" : .id,
} else {
  "myId" : 404,
  "message" : "Missing Id"
},
"myType" : .type
```
Is causing: 
```
com.schibsted.spt.data.jslt.JsltException: Parse error: Encountered " "," ", "" at line 6, column 2.
Was expecting one of:
    <EOF> 
    "or" ...
    "and" ...
    "==" ...
    "!=" ...
    ">=" ...
    ">" ...
    "<" ...
    "<=" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "|" ...
    ```

**Comment by larsga** [comment]
I'm confused as to what you think the final `, "myType" : .type` means. It's outside of both your objects (surrounded by `{}`), right? So how should JSLT interpret it?

What you have, syntactically, is:

```
  if (...) value1 else value2
  , "myType" : .type
```

How is JSLT supposed to connect that with the `if`?

**Comment by larsga** [comment]
> So the curly brackets are not marking the scope of if-else but they are creating a JSON object?

That's right. It looks like what you want is probably:

```
{
  "myId": if (.id) .id else 404,
  "message" : if (not(.id)) "Missing Id", // will be omitted if no value
  "myType" : .type
}
```

Note that it's also possible to use `+` to combine JSON objects.

**Comment by moienGoli** [comment]
I see,  it all makes more sense now Thanks.

**Comment by moienGoli** [comment]
I am using JSLT with an object filter which allows me to include null values. 
```
      final Expression resultTransformation =
          new Parser(transformationReader)
              .withObjectFilter("true")
              .compile();

```

This is to keep backward compatibility with my current API users. They are expecting certain keys to always be available even if their value is null. But at the same time certain keys should only be available under certain circumstances, e.g when they have a non null value.  

Is there an straight forward way to achieve this? 

I think in the code below, the compiler might complain about "key" 
```
{
  "myId": if (.id) .id else 404,
   if (not(.id)) "message": "Missing Id", 
  "myType" : .type
}
```

**Comment by moienGoli** [comment]
Only thing that I could came up with was to tag those values and have a custom object filter that filters out certain tags. 


```
{
  "myId": if (.id) .id else 404,
  "message" : if (not(.id)) "Missing Id" else "$IGNORE"
  "myType" : .type
}
```

Then have an object filter like this

```
.withObjectFilter(value -> !"$IGNORE".equals(value.asText()))
```

Probably not the cleanest way 😅
