### ISSUE TITLE
How to merge object to one result ? 

### ISSUE THREAD

**Issue by ca7erina** [schibsted/jslt#31]
I have input Json: 
```
{
  "data": [
    {
      "A": 12,
      "B": 23,
      "C": 15
    },
    {
      "A": 22,
      "B": 13,
      "C": 16
    }
  ]
}
```
Expected output 1: get the max value of each key.
```
{
  "A": 22,
  "B": 23,
  "C": 16
}
   
```
Expected output 2: merge the values of same key to an array? 
```
{
  "A": [12,22],
  "B": [23,13],
  "C": [15,16]
}
```
Is Jslt able to do those two kinds of transform ?

**Comment by larsga** [comment]
It's best to produce output 2 first, and then output 1 from that.

The `group-by` macro introduced in the experimental module makes it easy to do output 2. (I'll add documentation tonight.)

If you write a recursive function `largest` that returns the largest value in an array you can easily use that to produce output 1 from 2, like this:

`{for ($output2) .key : largest(.value)}`

**Comment by ca7erina** [comment]
Thanks Iarsga ! 
I'm also having a hard time to write the "largest( )" .
Input:
```
{"A":[10,12,13,14,15]}
```
JSLT: I have an idea about it but it just doesn't work for me T.T
```
def largest(arr)
 let temp = 0
 for($arr) if (. > $temp) ($temp=.)
 temp

{
 "A" : largest(.A)
}
```
Please help!

**Comment by larsga** [comment]
Once you know the technique it's easy:

```
def largest(arr)
  if (not($arr))
    0
  else
    let temp = largest($arr[1 : ])
    if ($temp < $arr[0])
      $arr[0]
    else
      $temp
```

**Comment by ca7erina** [comment]
Cool! Thanks a million! 
Can I test the "group by" at your online host soon (http://spt-data-dev-public-web.s3-website-eu-west-1.amazonaws.com/jstl2.html) ? 
let me know when you finish the documentation :+1:

**Comment by ca7erina** [comment]
I got it working now finally !!! It gives me the result of 1.
This rule probably can be optimized by group by.

```

def largest(arr)
  if (not($arr))
    0
  else
    let temp = largest($arr[1 : ])
    if ($temp < $arr[0])
      $arr[0]
    else
      $temp

def smallest(arr)
  if (not($arr))
    99999999
  else
    let temp = smallest($arr[1 : ])
    if ($temp > $arr[0])
      $arr[0]
    else
      $temp


{
 "A" : largest(flatten([for (.data)[for (.) .value if (.key=="A")]])),
 "B" : largest(flatten([for (.data)[for (.) .value if (.key=="B")]])),
 "C" : largest(flatten([for (.data)[for (.) .value if (.key=="C")]]))
}
```

**Comment by larsga** [comment]
Yes, with `group-by` you can get rid of the hard-wiring of the keys here. The documentation should show you how: https://github.com/schibsted/jslt/blob/master/docs/experimental.md

**Comment by ca7erina** [comment]
Thanks for always being so helpful.

**Comment by larsga** [comment]
I'm going to close this one, since it looks like we solved the issue.
