### ISSUE TITLE
preserve null objects and empty arrays

### ISSUE THREAD

**Issue by marcelocchdi** [schibsted/jslt#319]
Dear, we found that we could not preserve the null object fields and empty array fields, we need to keep these fields in the result after the transformation.

**Comment by larsga** [comment]
How to deal with that issue is explained [in the API docs](https://github.com/schibsted/jslt/blob/master/docs/api.md).

**Comment by marcelocchdi** [comment]
Dear, good afternoon, the documentation was very easy to understand and our transformation was successful, thank you very much again.
