### ISSUE TITLE
Can I import jslt from another jslt ?

### ISSUE THREAD

**Issue by ca7erina** [schibsted/jslt#33]
Im thinking that create a jslt lib has many def methods, and import it from any other jslt?

1. myLib
```
def largestValue(arr)
  if (not($arr))
    0
  else
    let temp = largestValue($arr[1 : ])
    if ($temp.value <= $arr[0].value)
      $arr[0]
    else
      $temp

def smallestValue(arr)
  if (not($arr))
   { "value":99999999}
  else
    let temp = smallestValue($arr[1 : ])
    if ($temp.value > $arr[0].value)
      $arr[0]
    else
      $temp

```

2. Any jslt that uses it 
```
import "http://xxx/methods" as myLib
...
myLib:smallestValue([...])
```

Is it possible to do that ?

**Comment by larsga** [comment]
I seem to have overlooked this one. Sorry!

If you JSLT file is on the classpath you can just do:

```
import "mylib.jslt" as myLib
...
myLib:smallestValue([...])
```

If it's not on the classpath then you can write a `ResourceResolver` that knows how to turn the import string into the JSLT file, and pass it to the parser. See http://static.javadoc.io/com.schibsted.spt.data/jslt/0.1.4/com/schibsted/spt/data/jslt/Parser.html
