### ISSUE TITLE
Wanted to replace convert the given input to a JSON and get a particular value 

### ISSUE THREAD

**Issue by kattagopi** [schibsted/jslt#338]
input : ["{\"ProjectMemberID\":\"\",\"TeamRoleCode\":\"\",\"TeamRoleName\":\"\",\"RoleCode\":\"\",\"RoleName\":\"Project Accountant\",\"Party\":{\"PartyID\":\"\",\"PartyTypeCode\":\"\",\"LegalEntityTypeCode\":\"\",\"PrimaryFlag\":\"\",\"PreviousPartyID\":\"\",\"testUserID\":\"123456\",\"OriginalPartyID\":\"\",\"RoleCode\":\"\",\"SuccessionSequenceNumber\":\"\"},\"FullName\":\"\",\"StartDate\":\"\",\"EndDate\":\"\",\"CostID\":\"\"}"]

I wanted to get value for Party.testUserID value

**Comment by larsga** [comment]
That should be easy to do, but remember the entire data is inside an array, so you need to pick the first element in the array first. That is, you need to start with `.[0]`.

**Comment by kattagopi** [comment]
Thanks @larsga  for helping out here.. this really helped in but the actual requirement changed with different format and faced a different issue
