### ISSUE TITLE
I wanted to convert the given input to JSON

### ISSUE THREAD

**Issue by kattagopi** [schibsted/jslt#339]
**input --**

[ "{\"BATCH_ID\":\"\"", "\"PM_PROJECT_REFERENCE\":\"2001-2402001 2024\"", "\"LINE_TYPE\":\"TASK\"", "\"TASK_NUMBER\":\"\"", "\"TASK_NAME\":\"\"", "\"START_DATE\":\"2024-04-01 00:00:00\"", "\"COMPLETION_DATE\":\"2024-04-01 00:00:00\"", "\"RESOURCE_LIST_ID\":\"\"", "\"PROCESS_FLAG\":\"N\"", "\"CREATED_BY\":\"1.1808\"", "\"LAST_UPDATED_BY\":\"1.1808\"", "\"CREATION_DATE\":\"2024-04-25 12:49:05\"", "\"LAST_UPDATE_DATE\":\"2024-04-25 12:49:05\"", "\"COST_ID\":\"hk-1\"}" ]

**Required out-Put:**
[
  {
    "BATCH_ID": "",
    "PM_PROJECT_REFERENCE": "2001-2402001 2024",
    "LINE_TYPE": "TASK",
    "TASK_NUMBER": "",
    "TASK_NAME": "",
    "START_DATE": "2024-04-01 00:00:00",
    "COMPLETION_DATE": "2024-04-01 00:00:00",
    "RESOURCE_LIST_ID": "",
    "PROCESS_FLAG": "N",
    "CREATED_BY": "1.1808",
    "LAST_UPDATED_BY": "1.1808",
    "CREATION_DATE": "2024-04-25 12:21:40",
    "LAST_UPDATE_DATE": "2024-04-25 12:21:40",
    "COST_ID": "hk-1"
  }
]

**Comment by larsga** [comment]
If you want help, perhaps you could show some sign that you at least put a minimal amount of effort into this. What did you try? What is your actual problem?

You opened an issue earlier, got a reply, and simply closed it with no comment. Not very pleasant for people trying to help you when you can't even be bothered to say whether we solved the problem for you or not.

**Comment by kattagopi** [comment]
I did try trim and replace functions and tried to do a split too using regex but it didn't help to remove or convert to JSON. So i have opened an issue to see if we have an open function to convert to some thing to parse to JSON

**Comment by larsga** [comment]
I see. I didn't notice that the difference between the input and output were that the first element in the input is a string.

Yes, the [from-json](https://github.com/schibsted/jslt/blob/master/functions.md#from-jsonstring-fallback---value) function does what you want.

**Comment by kattagopi** [comment]
Thanks for the quick reply @larsga  I tried and its not parsing and attaching screenshot for reference
![from-json](https://github.com/schibsted/jslt/assets/162556006/3c197f9a-f818-4641-be20-38763f219600)

**Comment by kattagopi** [comment]
Do we have a function that converts an Array to JSON??

**Comment by larsga** [comment]
The array is already JSON. What you need to do is to get hold of the string inside it so you can give it to `from-json`.

Please do look at the response to the previous issue.

**Comment by catull** [comment]
@kattagopi 

This will never work.
For starters, you need to pre-process your input.
JSLT is not meant to be given badly formatted pseudo-JSON.

Your input look like an array of strings, almost valid JSON if you squint.

But the first of those strings is a partial JSON object.  It starts with '{' followed by the attribute `BATCH_ID`, but it does not end with '}'.

What you need to do in e.g. Java, is to transform the input string into valid JSON.
In Java crude code:

```java
public class Crude {
    public static void main(final String[] args) {
        String input = "[ \"{\"BATCH_ID\":\"\"\", \"\"PM_PROJECT_REFERENCE\":\"2001-2402001 2024\"\", \"\"LINE_TYPE\":\"TASK\"\", \"\"TASK_NUMBER\":\"\"\", \"\"TASK_NAME\":\"\"\", \"\"START_DATE\":\"2024-04-01 00:00:00\"\", \"\"COMPLETION_DATE\":\"2024-04-01 00:00:00\"\", \"\"RESOURCE_LIST_ID\":\"\"\", \"\"PROCESS_FLAG\":\"N\"\", \"\"CREATED_BY\":\"1.1808\"\", \"\"LAST_UPDATED_BY\":\"1.1808\"\", \"\"CREATION_DATE\":\"2024-04-25 12:49:05\"\", \"\"LAST_UPDATE_DATE\":\"2024-04-25 12:49:05\"\", \"\"COST_ID\":\"hk-1\"}\" ]";
        String input2 = input
                .replaceAll("\"\\{", "{")    // transform "{" => {
                .replaceAll("\"}", "]")      // transform "}" => }
                .replaceAll("\", \"", ", "); // transform ", " =" ,
        System.out.println(input2);
    }
}
```

`input2` now contains valid JSON.

This, my friend, is what you should have done, NOT hope that JSLT does the job for you.
You have to learn and study what JSON is, how its format looks like, and how you can use it.

You mentioned you tried trim, trim only discards extra white-spaces, perhaps you meant stripping extra double quotes.

**Comment by catull** [comment]
If you paste your original input into the form at https://jsonformatter.curiousconcept.com/, it will give you lots of errors, hopefully you will clue in and better understand the matter.

**Comment by kattagopi** [comment]
well it helped where in am trying to something like this.. Thank you

from-json(replace($array,",?null,?", ""))

**Comment by catull** [comment]
Can you elaborate ?
What is exactly contained in `$array` ?

**Comment by kattagopi** [comment]
its input value >> above JSON array string..

**Comment by catull** [comment]
@kattagopi You know, for having 2 guys here trying to help you, for free, you sure are very stingy with information.
How do you think are we gloing to react next time ?
How are we to understand this:

its input value >> above JSON array string..

If by that you mean, in your editor, above the line

```
from-json(replace($array,",?null,?", ""))
```

then good for you.

Just put yourself in our shoes.

Would you want to help a guy you have never met, if he gives you practilally zero context ?
I definitely would not.

Which part of "elaborate" did you not understand ?

Continue this way, and expect ....... not much help.
