### ISSUE TITLE
How the Object Key Filter work

### ISSUE THREAD

**Issue by ext-singlad** [schibsted/jslt#370]
Hi,

We have been using this library and incredibly happy with the results, saves our lot of time in Json transformations.

We have a scenario where it is required not to omit the keys where value is null or empty string.
I found that this can be achieved as explained here - 
https://github.com/schibsted/jslt/blob/master/docs/api.md#object-key-filter

Now in the given syntax if I replace the filter with `". == null or . == {} or . == []"` I don't get the desired result, I am getting emply json in the output, when I pass true, I get the expected results. Can you please help me with the correct way how to pass the `. == null or . == {} or . == []' in the filter?
 

```
Expression e = new Parser(reader)
  .withObjectFilter(". == null or . == {} or . == []")
  .compile();
```

JSLT:
```
{
        "commodity": {
            "en": .COMMODITY_NAME_EN,
            "zh": .COMMODITY_NAME_ZH
        }
    }
```

Input Json:
```
{
"COMMODITY_NAME_EN": "ABC",
}
```

Expected Output Json:
```
{
        "commodity": {
            "en": "ABC",
            "zh": null
        }
    }
```

**Comment by larsga** [comment]
By default JSLT omits some values from objects, such as null. By setting the filter you can provide a new rule for what should be omitted. Basically, JSLT omits a value when the filter returns `false`.

So if the filter is `true` then no values are omitted, since the filter always evaluates to `true`. You're basically turning filtering off. That sounds like what you want?

**Comment by ext-singlad** [comment]
With true it is working fine.
how about if I have to discard values fields only if the value is null(. == null) and retain all other fields with empty json({}) and array([]).

**Comment by larsga** [comment]
You want the filter to return `true` when the value should be *omitted*, right? So you want `. != null`.

**Comment by ext-singlad** [comment]
yes that's correct.

**Comment by larsga** [comment]
That's good. Can we close this issue now?

**Comment by ext-singlad** [comment]
Sorry bit confused.
If I pass in the filter ". == null"
will it only consider null and omit others or vice versa.

**Comment by larsga** [comment]
The filter says what to keep. So if you say `. == null` it means you only want to keep null.

**Comment by ext-singlad** [comment]
But it is not working. if I am passing `. == null` getting empty json `{}` in the output for the shared example.

**Comment by larsga** [comment]
This is my previous comment. It explains why you get an empty JSON:

> So if you say . == null it means you only want to keep null.
