### ISSUE TITLE
Add a `has-key()` function 

### ISSUE THREAD

**Issue by ecerulm** [schibsted/jslt#38]
The `has-key(obj, 'x')` should be equivalent to 

```
is-object($o) and contains("key", $o)
```

On a first glance it may seems that just `.x` checks for the existence of key `x` but

* what if  . is an array
* what if . contains key `x` but the value is null or a falsy value

**Comment by larsga** [comment]
Hmmmm. It might be useful, but on the other hand it's so easy to do yourself. I'm inclined to wait on this one.
