### ISSUE TITLE
Idea: Java functions

### ISSUE THREAD

**Issue by vectro** [schibsted/jslt#4]
Sometimes you may want to do a transform that is easy in Java but hard in jslt. My use case is parsing/converting timestamps of different formats, but you can use your imagination: Decoding base64 data, inner joins, deduplication, etc.

So, my proposal is that jslt should support defining custom functions in Java which can then be referenced from the jslt code.

Implementing this would mitigate many of the other wishlist items since they could be implemented as custom functions.

**Comment by larsga** [comment]
This is definitely a use-case, and it's one that's already covered. You reminded me that I'd started on a tutorial on how to do this, but not checked it in.

I added it now: https://github.com/schibsted/jslt/blob/master/extensions.md

**Comment by vectro** [comment]
Neato!

**Comment by larsga** [comment]
I guess we can close this now?

**Comment by vectro** [comment]
Sounds right to me.

**Comment by ReddeppaKollu** [comment]
do we know how to call from jslt file, with custom function- i need base64 encode & decode, i have java functions but calling from jslt file is not clear

**Comment by larsga** [comment]
Yes, you can write a JSLT function in Java and plug it in. How to do it is documented here https://github.com/schibsted/jslt/blob/master/extensions.md
