### ISSUE TITLE
Global variables can't be referenced from functions

### ISSUE THREAD

**Issue by larsga** [schibsted/jslt#42]
The following should return 15, but gives an error because `$other` is not defined:

```
let other = 5

def test(obj)
  $obj + $other

test(10)
```

**Comment by larsga** [comment]
The problem is that the scope is not communicated to the inside of the function:

`public JsonNode call(JsonNode input, JsonNode[] arguments) {`

We need a different interface for declared functions, basically.

**Comment by vbartacek** [comment]
I've faced the same issue in past, but I did not realized that it was a bug :)

I am not sure which minimal Java version is supported. But for Java 8+ a default interface method would result in backward compatible change (same order of parameters like in the `Expression.apply(...)`:

```java
    default JsonNode call(Map<String, JsonNode> variables, JsonNode input, JsonNode... params) {
        return call(input, params);
    }
```
BTW it would be better to encapsulate all the arguments into one value object, so there could be added more parameters in future.

**Comment by larsga** [comment]
I'm not going to change the interface for functions written in Java, because those should not depend on the scope. So this will be for the own-declared functions only.

A related challenge here is that it's going to bring up the same issue for functions declared in imported modules, but those have a different scope. So something more sophisticated than the most obvious solution will be needed here.

**Comment by larsga** [comment]
The [variable-scope](https://github.com/schibsted/jslt/tree/variable-scope) branch has a fix for this issue. It also has a complete reworking of how variables are handled in JSLT, replacing the slow, clumsy `Map` objects and nested `Scope` objects with stack frames that are flat arrays. 

The result is that global variables now behave correctly, `queens(10)` runs 25% faster, and one of the big Schibsted transforms runs 10% faster.

I still want to review my own code, because there probably are some ugly things in there that I have forgotten. Also, there are quite a few optimization opportunities that haven't been made use of yet.
Plus, this may need some more testing.

If you are interested in this, please check out the branch and try your own transforms with it to verify that they work as they should. All bug reports very welcome.

**Comment by larsga** [comment]
Merged in the variable-scope branch now, solving this issue.
