### ISSUE TITLE
Add a hash function that returns a number (integer) instead of a string

### ISSUE THREAD

**Issue by ecerulm** [schibsted/jslt#44]
The existing `sha256-hex()` function provides an excellente hashing function that returns a string. There are some use cases where an integer result is more convenient in order to perform:

* `modulo(hash-int(.property), 100) == 0`  when you need a deterministic way to select a portion of input objects
* range checks on the results ,

 I see that there the original proposal for  a hash function was [hash-code()](https://github.com/schibsted/jslt/pull/36)  which indeed returned an integer. that was later changed to the current [sha256-hex](https://github.com/schibsted/jslt/blob/master/functions.md#sha256-hexstring---string). 

My proposal it to recover the original `hash-code()`  function for those cases where an integer result is more convenient.

**Comment by larsga** [comment]
Hmmmm. This is interesting. Implementation is easy: Jackson implements `equals` in the node classes, so we can simply use Jackson's `hashCode`. Except, that is, that in some cases Jackson says `!a.equals(b)` where JSLT says `a == b`. I think that should be manageable, though.

**Comment by ecerulm** [comment]
I went ahead and added a preliminary implementation of `hash-int` in PR #45

**Comment by ecerulm** [comment]
So summarizing

Alternatives: 
* `hash-int-v1`: Implemented in PR #45. This serializes the JSON object to a string and takes the `.hashCode()` of the resulting string. Two JSON objects will have the same `hash-int()` if they serialize to the same output.
* `hash-int-v2`: Implemented in #94. This traverses the `JsonNode` tree representation of the object, visiting each node and adding the `.hashCode()` of the underlying type (int, string, etc)  to the hash-int value to return. This avoid potentially costly string serialization
* `hash-int-v3`: `sha256-hex` and taking the `hashCode` of the resulting string. This is really equivalent to `hash-int-v1` since `sha256-hex` actually serializes the object to a string as well. 

I did a **benchmark** and performance of `hash-int-v1` and `hash-int-v3` is the same , `hash-int-v2` is slightly faster (~7% faster).  

`hash-int-v1` has IMHO a more straightforward implementation than `hash-int-v3`, but `hash-int-v3` is faster. 

@larsga would you approve #45 or #94 ?

**Comment by ecerulm** [comment]
I guess this will be included in next release. When do you plan to release 0.1.9?

**Comment by larsga** [comment]
It will be included, yes. I'm thinking it's about time we did 0.1.9. I want to get it out before I start on the `|` operator.
