### ISSUE TITLE
Configure jslt to include keys for null or {} values instead of omitting the key

### ISSUE THREAD

**Issue by Mohammadcore** [schibsted/jslt#51]
Currently keys with null or {} or [] value are omitted. Is there a way to configure this behavior or where in code can I patch this so I force it to include empty/null keys as well.

**Comment by larsga** [comment]
This is something I was thinking we'd have to make configurable at some point. How do you want to configure it? Would a JSLT expression as filter work?

**Comment by Mohammadcore** [comment]
Would it have the flexibility of having control over each key (to include or not if null). Or would it be a filter that applies to all keys i.e. include **all** null keys or exclude **all** null keys.

**Comment by larsga** [comment]
I would say a filter to apply to all keys. If you want to control which key is included or not included you can handle that in the transform itself.

**Comment by Mohammadcore** [comment]
let's say it's a filter to apply to all keys. Yet for a use case might be needed to have control per key rather than globally.

Example:
```
let doestExists = functions:find($arg1)
let doestExistsEither = functions:find($arg2)
{
  "foo" : doestExists,
  "bar" : doestExistsEither
}
```
With following use cases:

### 1
```
{
  "foo" : null,
}
```
### 2
```
{
  "foo" : null,
  "bar": null
}
```
### 3
`{}`

**Comment by larsga** [comment]
But you already have full control per key in the template. I don't think giving you that control in the filter actually helps you any. It just moves the challenge somewhere else, and complicates the system.

I think I made my mind up:

- filter applies to all values (of keys)
- filter can be specified in JSLT
- filter can _also_ be specified in Java, if desired

**Comment by larsga** [comment]
It's true that you can't necessarily change other people's templates, but you can use them as input to your own template. At which point we're back where we started: making the template do what you want is just as easy as doing it in the filter.

I'll make the change. This may require a deeper change in the JSLT API, due to poor initial design. But I'll solve that.

**Comment by larsga** [comment]
That commit implements the filters, fixing this issue. @Mohammadcore Would be great if you could test this out.

**Comment by jerrybyte** [comment]
Hi @larsga , how can I keep the null value in JSLT ? I cannot find any spec. Thanks in advance
