### ISSUE TITLE
[request for help] Adding properties to existing nodes

### ISSUE THREAD

**Issue by nicosensei** [schibsted/jslt#53]
Hi,

Let's consider the 2 following JSON documents that schematize a use case I have:

```
{
    "children": {
       "child": {
           "pseudo_csv": "v1:v2",
           "a_tag": "foo"
       }
   }
}
```

and

```
{
    "children": {
       "child": [
         {
           "pseudo_csv": "v1:v2",
           "a_tag": "foo"
         },
         {
           "pseudo_csv": "w1:w2",
           "another_tag": "bar"
         }
      ]
   }
}
```

When I receive input documents, I can have either a single node or an array for `.children.child`. Additionnally I can't predict the set of properties in each `child`, apart from `pseudo_csv` which is guaranteed to be present ...

I would like to write a JSLT transform that would respectively produce the following outputs :

```
{
    "child": {
        "prop_1": "v1",
        "prop_2": "v2",
        "a_tag": "foo"
   }
}
```

and

```
{
    "child": [
         {
           "prop_1": "v1",
           "prop_2": "v2",
           "a_tag": "foo"
         },
         {
           "prop_1": "w1",
           "prop_2": "w2",
           "another_tag": "bar"
         }
      ]
   }
}
```
So I'd like to flatten the `children.child` hierarchy and simply keep one level, and for each `child`, break a given "pseudo-CSV" property into a set of properties, and add every other property to the document.

I'm actually struggling to write the JSLT. I really need it to be dynamic, I can't use object matching.

**Comment by nicosensei** [comment]
My best attemp so far is:

```
def process_children(value)
  if (is-array($value)) [ for ($value) process_child(.) ]
  else
   process_child($value)

def process_child(value)
  let split = split($value.pseudo_csv, ":")

  {
    "prop_1": $split[0],
    "prop_2": $split[1],
    "src": { for ($value) .key : .value
      if (.key != "pseudo_csv")}
  }

{
  "child": process_children(.children.child)
}
```

which _almost_ does the trick! Except I'd like to remove the `src` container, and instead copy all properties to the object I'm building... I can't find a way to do so.

**Comment by nicosensei** [comment]
Of course I could write an extension function in Java, and that's going to be my workaround for now, but it'd be nice to have a native solution.

**Comment by larsga** [comment]
It looks like you've pretty much solved this. The magic solution for extending an object is to use `+` to merge the objects. So if you write:

```
  {
    "prop_1": $split[0],
    "prop_2": $split[1]
  } + { for ($value) .key : .value
      if (.key != "pseudo_csv")}
```

you should have your solution, if I understand what you want correctly.

**Comment by nicosensei** [comment]
Ok, I finally solved it :-)

Here's the JSLT I obtained:

```
def process_children(value)
  if (is-array($value)) [ for ($value) process_child(.) ]
  else
   process_child($value)

def process_child(value)
  let split = split($value.pseudo_csv, ":")

  let computed = {
    "prop_1": $split[0],
    "prop_2": $split[1]
  }

  let filtered = { for ($value) .key : .value
      if (.key != "pseudo_csv")}
  
  let joined_array = flatten([ array($computed), array($filtered) ])

  { for ($joined_array) .key: .value }

{
  "child": process_children(.children.child)
}
```
Suggestions to improve / simplify it will be most welcome!

**Comment by nicosensei** [comment]
Sorry I had the page open, so I just saw your reply. Thanks a lot, it's simpler than my template!

**Comment by larsga** [comment]
Good we have it solved. I'll close the issue, then. 👍
