### ISSUE TITLE
Boolean operators in if statement

### ISSUE THREAD

**Issue by nicosensei** [schibsted/jslt#54]
Hi,

Is it possible to combine(boolean and, or) tests in an if statement? I would need it to test ranges against a numeric field.

I can't find this is the language tutorial or in the exemples.

**Comment by nicosensei** [comment]
Oh ok great! Unless I'm blind or very distracted, this is not present in the language tutorial, so it should probably be added.

Thank you for this super fast reply, and have a great weekend!

**Comment by larsga** [comment]
It's in the tutorial, but very brief. I'll expand it a little to make it harder to miss.
