### ISSUE TITLE
[request for help] Generating dynamic keys in a JSON object

### ISSUE THREAD

**Issue by nicosensei** [schibsted/jslt#55]
Hi,

Another language question! 

Let's consider the following JSON input: 

```
{
  "filter" : {
    "field" : "aField",
    "terms" : [ "valueA", "valueB" ]
  }
}
```

I would like to transform into the following snippet : 

```
{
  "filter" : [
    {
       "terms": {
           "aField": [ "valueA", "valueB" ]
       }
    }
  ]
}
```
So it implies to be able to dynamicaly generate keys in the target JSON based on the value of `.filter.field`.

So far I've been able to achieve this goal by using the `from-json` function and generate my JSON as a string like this:

```
from-json("{
  \"filter\": [
    {
      \"terms\": { 
        \"" + .filter.field + "\": " + .filter.terms + "
      }
    }
  ]
}")
```
That's not quite elegant though, and would become a pain for more complex JSON structures.

I'm looking for something like: 
```
{
  "filter": [
    {
      "terms": { 
        string(.filter.field) : .filter.terms
      }
    }
  ]
}
```

however this does not compile. Am I missing something?

**Comment by larsga** [comment]
The trick here is to use the object comprehension syntax:

`{for (<array to loop over>) .key : .value}`

By creating an array of a single object you can get what you want:

```
{
  "filter" : [
    {
       "terms": {for ([.filter])
           .field : .terms
       }
    }
  ]
}
```

I guess we can discuss whether dynamic keys should be allowed or not. Perhaps they should be allowed.

**Comment by nicosensei** [comment]
Ok, thank you that's very helpful. I had not figured this quirk on my own ;-)

I think dynamic keys would be quite useful.
