### ISSUE TITLE
Substring and/or string replace?

### ISSUE THREAD

**Issue by kalbmj** [schibsted/jslt#57]
Hello,

Looking at JSLT and trying to fit it to some simple transformations like "take the first two chars of this field" and "replace all spaces with underscores". 

Example, would be something like:
```
{
   "output1": substring(.input1.id, 0, 2),
   "output2": replace(.input2, " ", "_")
}
```

Is this something anyone is doing right now, and if so are you using an existing built-in function (I see there's regex, but is there anything like replace and substring modeled above), or through your own defined functions?  

Thanks in advance.

**Comment by larsga** [comment]
You can do substring with slicing: `"output1": .input1.id[0 : 2],`

That could probably be documented better, so I'll look into that.

The replace function has been overlooked, sadly. We really do need to add that one. In the meantime, you can work around it with:

```
def replace(source, in, out)
  join(split($source, $in), $out)
```

**Comment by kalbmj** [comment]
Thank you @larsga for the feedback, was able to get the substring working as needed. 

One more question (let me know if you'd like me to open a separate support issue), is there a particular syntax that can/should be used if inside of a "def" we would like to put a "let", for example:
`def getCode( incomingValue )
	let firstTwo = $incomingValue[0 : 2]
	if($firstTwo == "01")
	    "01"
	else
	    "99"``

Right now, on the line after this expression, I'm getting :+1: 
`com.schibsted.spt.data.jslt.JsltException: Parse error: Encountered " "let" "let "" at line xx, column 1.
Was expecting one of:
    <EOF> 
    "or" ...
    "and" ...
    "==" ...
    "!=" ...
    ">=" ...
    ">" ...
    "<" ...
    "<=" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
     at <unknown>:55:17
	at com.schibsted.spt.data.jslt.parser.ParserImpl.compileExpression(ParserImpl.java:56) ~[jslt-0.1.5.jar:na]
	at com.schibsted.spt.data.jslt.Parser.compile(Parser.java:190) ~[jslt-0.1.5.jar:na]
	at org.act.leap.util.JsltUtils.loadJsltFromResource(JsltUtils.java:108) 
...`

Thanks in advance.
