### ISSUE TITLE
Is there an easy way to do trimming, padding and replace of strings in jslt?

### ISSUE THREAD

**Issue by NairR9** [schibsted/jslt#59]
Hello,

We are using JSLT to achieve dynamic mapping configurations.
But couldn't find a quick way to do string functions like trim, padding, replace etc.

Would you have any pointers for the same?

**Comment by larsga** [comment]
I was actually just working on the `replace` function, and have done some of the tests. You're looking for something like this, right?

```
replace("hey-ho-ho", "-", " ") => "hey ho ho"
```

With `trim` you're thinking something that removes leading and trailing whitespace? Sure, I can add that. It probably should have been there already.

For `padding`, can you be more specific about what you had in mind?

**Comment by NairR9** [comment]
Thanks for getting back on this.
The scenarios you described for `trim` and `replace` is exactly what we are looking for.

For `padding`, it would be something like : field fileNumber needs to be 8 digits always, but incase it comes as only with 5 digits, then we append three  0's to the end or maybe to the beginning, whichever is applicable. It could be 0's or empty spaces or dashes..etc.

**Comment by larsga** [comment]
I think there are some missing spaces in your example, but basically like this, then?

```
def lpad(str, length, pad)
  if (size($str) < $length)
    $pad * ($length - size($str)) + $str
  else
    $str

lpad("123", 5, "0") => "00123"
```

Those are pretty easy to define yourself.

**Comment by NairR9** [comment]
Thanks...that looks good.
I was hesitant to define it that way as I wasn't sure if `*` operator works the same way for strings as well.
So if I was appending spaces instead of 0, I should still be good using `*` ?

**Comment by NairR9** [comment]
Actually looks like you have used 0 as a string and not as a number, so looks like `*` should work on strings

**Comment by larsga** [comment]
You can use `*` to multiply a string with a number. That will give you the string repeated that many times.

I'll see if I can add `replace` and `trim` pretty quickly.

**Comment by larsga** [comment]
`replace` was added in commit d9b6ff3c3f0df4577e22160fa46ab9e76a821a6a

**Comment by larsga** [comment]
`trim` was added in commit fc2000e5bd33ef0aa275d995df88cf81ffb084a6

I believe that solves the issue. Feel free to continue the discussion if you disagree, and we can reopen.

**Comment by NairR9** [comment]
Thank you, will use the latest version and check

**Comment by NairR9** [comment]
Hello,

Will you be releasing the latest updates soon to the repository?
Could not find an updated version in maven repo.

Thank you.

**Comment by larsga** [comment]
It won't happen this week, but I can do it next week. You need the release to get these latest functions? If so, I can make a release on Monday or thereabouts.

**Comment by catull** [comment]
This may work when used in Java, however in the demo app, it trips up an exception.

**Input**
```json
{
   "publicationDate": "2019-03-18"
}
```

**JSLT**
```
{
  "pubDate": replace(.publicationDate, "-", "")
}
```
**Result**
```
ERROR: com.schibsted.spt.data.jslt.JsltException: No such function: 'replace' at <inline>:3:16
```

This works:

```
{
  "pubDate": join(split(.publicationDate, "-"), "")
}
```

The result here is:
```json
{
  "pubDate": "20190318"
}
```

**Comment by larsga** [comment]
@catull I managed to update the online demo now. Thanks for reminding me!
