### ISSUE TITLE
Grouping by a repeated ID

### ISSUE THREAD

**Issue by rudolfv** [schibsted/jslt#62]
@larsga I would like to perform the following transform. I apologize if this has already been covered in documentation/another issue. I had a look, but could not find anything.

```
{
  "details": [
    {
      "childID": "1",
      "mainID": "abc",
    },
    {
      "childID": "2",
      "mainID": "abc",
    },
    {
      "childID": "3",
      "mainID": "def",
    }            
  ]
}

{
  "groupedDetails": [
    {
      "mainID": "abc",
      "childIDs": [
        "1",
        "2"
      ]
    },
    {
      "mainID": "def",
      "childIDs": [
        "3"
      ]
    }
  ]
}
```

I have a good idea how to do this once I have an array of unique mainIDs, but I'm missing that part.

**Comment by rudolfv** [comment]
Looks like the experimental group_by macro can be used to resolve this. Is that correct? https://github.com/schibsted/jslt/commit/2fc8b669dd48949253933e2d5a611f9036a30f41

**Comment by larsga** [comment]
Yes, that is correct. It's documented here: https://github.com/schibsted/jslt/blob/master/docs/experimental.md

Would be interesting to hear back how the macro works for you.

**Comment by rudolfv** [comment]
@larsga This seems to work very well. I have implemented as follows as I needed additional fields. Is that the best approach?

```
def getDetail(details, childID)
  let detailArr = [for ($details) . if (.childID == $childID)]
  $detailArr[0]

let groupedDetails = exp:group-by(.details, .mainID, .childID)
let details = .details

{
  "groupedDetails": [for ($groupedDetails)
    {
      "mainID" : .key,
      "children": [
        [for (.values)
          let detail = getDetail($details, .)
          {
            "childID" : .,
            "otherField" : $detail.otherField
          }
        ]
      ]
    }
  ]
}
```

**Comment by larsga** [comment]
That join you are doing in `getDetail` is quite expensive, and it's also not necessary, because `group-by` doesn't just produce a list of unique keys for you. It also collects the values for each key. So you can simplify this by doing:

```
import "http://jslt.schibsted.com/2018/experimental" as exp

{
  "groupedDetails": [for (exp:group-by(.details, .mainID, .childID))
    {
      "mainID" : .key,
      "children": .values      
    }
  ]
}
```

**Comment by rudolfv** [comment]
I think you might have missed that the fact that I also need an "otherField" which is linked to the childID. From what I can see .values will only return an array of childIDs, not other fields too. This was not stated clearly in my original example:


```
{
  "details": [
    {
      "childID": "1",
      "mainID": "abc",
      "otherField": "aaa"
    },
    {
      "childID": "2",
      "mainID": "abc",
      "otherField": "bbb"
    },
    {
      "childID": "3",
      "mainID": "def",
      "otherField": "ccc"
    }            
  ]
}

{
  "groupedDetails": [
    {
      "mainID": "abc",
      "children": [
         {
            "childID": "1",
            "otherField": "aaa"
         },
         {
            "childID": "2",
            "otherField": "bbb"
         }
      ]
    },
    {
      "mainID": "def",
      "children": [
         {
            "childID": "3",
            "otherField": "ccc"
         }
      ]
    }
  ]
}
```

**Comment by larsga** [comment]
Yes, that changes things a little bit. But note in the `group-by`: when you say `.childID` in the last argument, you're saying that's what you want to pick out from the grouped objects. If instead you say `.` then you keep the whole object instead of just the ID. Then you don't have to go look up the object again later.

So for `.key == "abc"`, `.values` would be:

```
[ {
      "childID" : "1",
      "mainID" : "abc",
      "otherField" : "aaa"
    }, {
      "childID" : "2",
      "mainID" : "abc",
      "otherField" : "bbb"
    } ]
```

Given that you can turn it into what you want with:

```
import "http://jslt.schibsted.com/2018/experimental" as exp

{
  "groupedDetails": [for (exp:group-by(.details, .mainID, .))
    {
      "mainID" : .key,
      "children": [for (.values) {
        "childID" : .childID,
        "otherField" : .otherField
      }]
    }
  ]
}
```

I guess object matching would be even nicer here, but that needs a bit more work before it can help you here.

**Comment by rudolfv** [comment]
Thank you very much. I was missing the blindingly obvious!

**Comment by larsga** [comment]
No need to be so hard on yourself: somehow `group-by` is quite tricky to get your head around. I struggle with it, too.

I find one way to make this easier to grasp is to use the playground and run the transform just outputting `.values` directly so I can see what it is before I start changing it.
