### ISSUE TITLE
nested * matcher does not work

### ISSUE THREAD

**Issue by cabaumgartner** [schibsted/jslt#63]
I have a large flat JSON object that I wish to convert to nested JSON. The * matcher does not seem to work inside of objects. 

Example JSLT:
{
  "parent" : .one,
  "nested" : {
    * : .
  }
}

Example input JSON:
{
   "one" : "1",
   "two" : "2"
}

Actual Result:
{
  "parent" : "1"
}

Expected Result:
{
  "parent" : "1",
  "nested" : {
     "two" : 2
  }
}

Am I missing something here?

Thanks.

**Comment by cabaumgartner** [comment]
OK, I just saw the example of nested matching, so I guess this is working as designed.

**Comment by larsga** [comment]
Yes, it is. The matcher assumes you want to match the same nesting structure.

If it did match you would also get the `one` field, because nothing in the matcher says you don't want it. (Referencing the field elsewhere is not enough to exclude it.)

Can we close this ticket?

**Comment by cabaumgartner** [comment]
Yes, you can close it.
