### ISSUE TITLE
Conditionally add target field

### ISSUE THREAD

**Issue by kalbmj** [schibsted/jslt#65]
Is there a way in jslt syntax where we could ONLY map a target field if some condition is met in the source,

For example 
Given inputs: 
{
  "a":"xxx",
  "b":"yyy"
}
and
{
  "a":"yyy",
   "b":"yyy"
}

I ONLY want to Output "anew" field if "a"=="y", otherwise I don't want it in the output json at all (null or otherwise). 
Please let me know if any more clarifications are needed, thanks in advance.

**Comment by larsga** [comment]
This is actually easy to do: just use an `if` to produce the value for that field:

```
{
  "b" : .b, // copy b unchanged
  "a" : if (.a == "yyy") .a
}
```

If the `if` test does not match the value of `a` will be `null`, and the whole field will be dropped from the output. That's what you wanted, right?

**Comment by kalbmj** [comment]
Thank you @larsga , I can't believe I missed that one.
