### ISSUE TITLE
Create lookup in a for loop

### ISSUE THREAD

**Issue by kalbmj** [schibsted/jslt#66]
Would it be possible to generate values and create a lookup in a for loop?  The goal is to only to iterate through the loop once, for performance, while setting multiple different (conditional) fields for output.
So one idea to change this existing example:
```
let lookup = {
  "no" : "Norway,
  "se" : "Sweden"
}
get-key($lookup, "no")
```

To something like:
```
let lookup = {
  [for (.) 
    if(.key == "a") "val1" : .value,
    if(.key == "b") "val2" : .value ]
}
get-key($lookup, "val1")
```

Let me know if you need any more information/clarification or have any other ideas on minimizing looping, and thanks in advance.

**Comment by larsga** [comment]
Maybe I don't fully get what you're trying to do, but wouldn't this do it? 

```
let lookup = {
  "val1" : .a,
  "val2" : .b
}

get-key($lookup, "val1")
```

If you want a more complex condition than "does `.a` exist" then you can use an `if (<condition>) .a` instead.
