### ISSUE TITLE
[Question] no plan to support javascript framework for jslt ?

### ISSUE THREAD

**Issue by Kwanghyuk-Kim** [schibsted/jslt#74]
Hello, nice to meet you, @larsga 

Recently, I am looking for js version of jslt framework. But, I cound't.
Is there no plan to support javascript version yet ?

**Comment by larsga** [comment]
Hi!

I'm afraid there are no plans for a JavaScript version. However, if someone wants to implement it I would be happy to help as far as I can.

**Comment by Kwanghyuk-Kim** [comment]
@larsga 
Ok,, thank you for your quick feedback. :)
