### ISSUE TITLE
Parse tree traversal

### ISSUE THREAD

**Issue by thorstenhilker** [schibsted/jslt#78]
Hi!
I know there is a similar issue on the wishlist:
"Implement parse tree traversal API."

Is there already a way to parse the json tree traversal?

Regards,
Thorsten

**Comment by larsga** [comment]
You want to traverse the representation of the JSLT query? It's possible to do, using the internal API, but could be easier than it is. Is there anything specific you are looking for, or trying to do?

**Comment by thorstenhilker** [comment]
Hi Larsga!

Thank you for your quick answer.
We want to traverse the whole json tree or a part of the tree, to visit all children. 
In the "wishlist" the following topic is mentioned: "Implement parse tree traversal API."
I wonder how it is possible to traverse the json without this api.
Do you have an example?
I would be very grateful.

Regards,
Thorsten

**Comment by larsga** [comment]
Ah, I see. You want to traverse the _JSON_ tree. That's easy. See the [flatten](https://github.com/schibsted/jslt/blob/master/examples/flatten.jslt) function for an example of how you can traverse recursively through JSON objects.

**Comment by thorstenhilker** [comment]
Hi!

Thank you again.
That looks good, but I've to consult our experts, if this is really that what we want. Looks good!

BTW: Great Framework!

Regards,
Thorsten
