### ISSUE TITLE
Loss of precision with parse-time/format-time

### ISSUE THREAD

**Issue by vectro** [schibsted/jslt#8]
This program does not yield the intended result:
`format-time(parse-time("2017-01-10", "yyyy-MM-dd"), "yyyy-MM-dd")`

Instead of returning `"2017-01-10"`, it returns `"2017-01-09"`.

I haven't debugged this but I assume it is due to a numerical instability issue within parse-time.

**Comment by larsga** [comment]
Checking quickly:

```
parse-time("2017-01-10", "yyyy-MM-dd") => 1.484006399998E9
```

```
format-time(1.484006399998E9, "yyyy-MM-dd") => parse error
```

So that's another bug.

**Comment by larsga** [comment]
Converting to another syntax:

```
format-time(1484006399.998, "yyyy-MM-dd") => "2017-01-09"
format-time(1484006399.998, "yyyy-MM-dd HH:mm:ss") => "2017-01-09 23:59:59"
```

Yeah, definitely a precision issue.

**Comment by vectro** [comment]
Looks like it is not exactly a precision issue, but rather a floating-point numerical instability issue. The Java double has 52 bits of precision in it, more than enough to hold this number (which is 41 bits long in integer milliseconds form).

The problem is that after diving by 1000, the number cannot be exactly represented in binary, regardless of the amount of precision. The result is rounded down ever so slightly (by roughly 10<sup>-22</sup> seconds) and then truncated when we convert it back to a long in format-date().

I will submit a patch to round the long instead of truncating.
