### ISSUE TITLE
Is getValue from Array possible ?

### ISSUE THREAD

**Issue by Maevy** [schibsted/jslt#80]
Hi,
i have the following problem. In the Json there is the following element

```
{
  "node1": "abc",
  "array1": [
    {
      "arrayValue1": "def"
    },
    {
      "arrayValue1": "fed"
    }
  ]
}
```

Now based on the documentation the for operation either creates an object or an array

```
def getValueFromArray()
 {for (.array1) "results" : .arrayValue1
  if(.arrayValue1== "def")

 }

{
 "arrayresult" : getValueFromArray()
}
```

the result is 

```
{
  "arrayresult" : {
    "results" : "def"
  }
}
```

Is it possible to simply return the value like this without a subobject ?

```
{
  "arrayresult" :  "def"
}
```

**Comment by larsga** [comment]
It's definitely possible, although exactly how to do it varies a little depending on exactly what you want.

```
{
  "arrayresult" : <expr>
}
```

If the rule is "I want to go inside the `array1` key, then pick the first object inside that, and get the value of the `arrayValue1` key inside there, then `<expr>` should be `.array1[0].arrayValue1`

But if you want the `arrayValue1` key of all objects inside `array1` then you want:

```
{
  "arrayresult" : [for (.array1) .arrayValue1]
}
```

**Comment by Maevy** [comment]
The point is the order in which i  can find my element can be random thus i am forced to iterate over it and i need only the value result and dont want to create a new object

**Comment by larsga** [comment]
I'm sorry, but I don't understand what you mean. What is the output that you want?

**Comment by Maevy** [comment]
```
{
  "node1": "abc",
  "array1": [  // The order in which elements are alligned is completely random here ! it can be position 0 or 1 or 50
    {
      "arrayValue1": "def"
    },
    {
      "arrayValue1": "fed"
    }
  ]
}
```

and my desired result is

{
  "arrayresult" : "def"
}

thanks for the help in advance

**Comment by larsga** [comment]
It makes sense that the objects in the array are randomly ordered, but then how can you tell which one of them you want as the output? If you know the output should be `"def"` then you can just write it statically, without walking through the array, right?

But let's assume the object contains something else as well, which is what you're really interested in. Then I would do this:

```
// pick out all the objects that satisfy our condition
let chosenObjects = [for (.array1) . if (.arrayValue1 == "def")]
// pick the first out of however many that might be
let chosenObject = $chosenObjects[0]
{
  "arrayresult" : $chosenObject.arrayValue1
}
```

Does this make sense?

**Comment by Maevy** [comment]
thats EXACTLY what i need, very clever, sadly my thoughts where to complex, THANKS !

**Comment by larsga** [comment]
No worries. :) I'm closing this issue as solved, then.
