### ISSUE TITLE
Variable as key

### ISSUE THREAD

**Issue by thorstenhilker** [schibsted/jslt#81]
Hi!

First of all I want to thank you for your great work! It is very helpful for us.

But one question came up:
Is it possible to use a variable as a key?

Here is an example:

Input:
{
  "x" : "y"
}

JSLT (Just a naive try):
let v = "x"
{
"a"  :  .$v
}

I thing you know what I mean. Is it possible?
Or is there a work around, maybe a function?

Regards!
Thorsten

**Comment by larsga** [comment]
The `.$v` construct doesn't really make sense, so, yes there is a function, `get-key`: https://github.com/schibsted/jslt/blob/master/functions.md#get-keyobject-key-fallback---value

**Comment by thorstenhilker** [comment]
Hi!
Thank you very much!
It's all in the manual. Did not read it carefully enough, sorry.
Perfect framework!

Regards,
Thorsten

**Comment by thorstenhilker** [comment]
Hi!

Is it possible to make some donation?
I’m only a freelancer at the https://www.gvl.de <https://www.gvl.de/>
Maybe I can achieve something, because a lot of transformation might be done via jslt.

Try my bet.

Regards,

Thorsten

**Comment by larsga** [comment]
Hi Thorsten,

That's very kind of you, but to be honest I don't think you should donate to this project. Funding is not an issue for JSLT. It's probably better if you donate to something else.

Yes, JSLT has many different kinds of uses. I'm hoping to be able to open source a bigger solution on top of JSLT for event pipelines later on. My work has a slightly different focus at the moment, but I'm hoping that will change soon.
