### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by ngsoftwaredev** [schibsted/jslt#82]
With JSLT template getting bigger and more complex, it would be very nice to be able to add comments, and thus make the life of fellow developers (and possibly mine in a couple months) a little easier ;-p

Since JSLT is a superset of JSON, I don't think it would be an issue. 

My only alternative right now is to add comments and then programmatically trim them before compiling. Not very elegant...

**Comment by larsga** [comment]
You can add comments, like this:

```
// this is a comment
.foo
```

**Comment by ngsoftwaredev** [comment]
Oh, my bad, I hadn't noticed it! Sorry for the confusion.

**Comment by larsga** [comment]
No worries :)
