### ISSUE TITLE
Is ist possible to receive null on Java Function extension instead of "null" when param null

### ISSUE THREAD

**Issue by Maevy** [schibsted/jslt#83]
Hi,
we have extended JSLT by a few function and noticed, that when we pass a null (our json object simply doesnt exist) in the Java Function the JsonNode contains a "null" instead of a real null which makes the If expression pretty risky since "null" could be a valid string. So is it possible to receive a real null ?

Kind regards

**Comment by larsga** [comment]
The principle in JSLT is that all values passed around in JSLT expressions are JSON. JSON does have a `null` value, but it's not represented the same way as Java `null`. A string `"null"` is just some random string and has nothing to do with proper nulls.

I'm not sure what you mean by "a real null", but all nulls in JSLT _must_ be represented as JSON `null`. So if your object doesn't exist, pass `NullNode.instance`. That will work.

You say "pass", but I guess you really mean "return" from the function? I found some issues with how JSLT handles that, which I will fix.

Perhaps you can give me an example of the JSLT, and a bit more detail about what goes into/out of the function? It's easier to see what's going on then.

**Comment by larsga** [comment]
Several things to say about this.

(1) You can use the `parse-time` function instead: https://github.com/schibsted/jslt/blob/master/functions.md#parse-timetime-format-fallback---double

(2) Your call to `.asText()` makes it impossible for you to distinguish between a `null` as input and a String `"null"` as input. Check `jsonNodes[0].isNull()` first to see if it's `null`. (The `parse-time` function does this for you.)

(3) Don't do this: `new TextNode(null)`. Far better to return `NullNode.instance`. Or, if you must have a string: `new TextNode("null")`.

**Comment by Maevy** [comment]
Ahh ok i wasn't aware that jackson manages to cast a null into a "null".

The thing with `parse-time` is that we are using `java.time.Duration` to get a full millisecond representation without a power notation to calculate it.

Anyways thx for help

**Comment by larsga** [comment]
That's up to you. Just letting you know there's a choice.

Closing this now, but feel free to open another one if you have more issues.
