### ISSUE TITLE
Flatten an array.

### ISSUE THREAD

**Issue by thorstenhilker** [schibsted/jslt#85]
Hi!

Is it possible to flatten an array like:

[{"a" : "1"},{"b" : "1"},{"c" : "1"}, [{"d" : "1"},{"e" : "1"},{"f" : "1"}]]

into 

[{"a" : "1"},{"b" : "1"},{"c" : "1"}, {"d" : "1"},{"e" : "1"},{"f" : "1"}]      ?

Regards,
Thorsten

**Comment by larsga** [comment]
Sure. Here's an example that does it with objects https://github.com/schibsted/jslt/blob/master/examples/flatten.jslt

That may help you see how to do it for arrays. If not, let me know and I'll write it up for you.
