### ISSUE TITLE
Do not omit null, {} or []

### ISSUE THREAD

**Issue by ws-joaosilva** [schibsted/jslt#86]
On [documentation ](https://github.com/schibsted/jslt/blob/master/tutorial.md#json-construction) it is present that 

> Note that if the expression evaluates to null, {}, or [] then the entire key is omitted from the constructed object. This is to avoid producing objects with lots of no-value keys.

Is there any configuration that i can use to avoid this omit of data?

**Comment by larsga** [comment]
You can configure this to work the way you want by doing:

```
new Parser(reader)
  .withObjectFilter( <your filter here> )
  .compile()
```

Then you get an `Expression` where this value omission works the way you want.

**Comment by larsga** [comment]
Correct. Great 👍

**Comment by larsga** [comment]
Documented this here https://github.com/schibsted/jslt/blob/master/docs/api.md#object-key-filter
