### ISSUE TITLE
Need to create an POST API that can transform the incoming json which is build with java-dropwizard. I can transform individual json objects , but how do I do this for multiple incoming json obejcts through an API call.

### ISSUE THREAD

**Issue by kiddo-7** [schibsted/jslt#88]
package com.app.resources.Transform;
import javax.ws.rs.;
import javax.ws.rs.core.;
@path("/api/v1")
public class Transform {
@post
@path("/changejson")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public String ChangeJson() {
// Need to implement this
return ChangedJson;
}

I'm able to change the key using
{
"changed-key": .Original_Key,
"changed-key-2" : ."Original New Key"
}
But How to include my jslt template as an API with dropwizard for processing large number of incoming json objects

Input Json ::

[ {

"Data-1": "Test1",
"Data-2" : "Test2",
"Data-3" : "Test3"
},

{

"Data-1": "Test1",
"Data-2" : "Test2",
"Data-3" : "Test3"
}, {

"Data-1": "Test1",
"Data-2" : "Test2",
"Data-3" : "Test3"
} ]

Expected Output ::

[ {

"KeyChange" : "Test1",
"KeyChange" : "Test2",
"KeyChange" : "Test3"
},

{

"KeyChange" : "Test1",
"KeyChange" : "Test2",
"KeyChange" : "Test3"
},

{

"KeyChange" : "Test1",
"KeyChange" : "Test2",
"KeyChange" : "Test3"
} ]

**Comment by larsga** [comment]
I'm not sure what you problem is, to be honest. Can't you use this example?

```
import com.schibsted.spt.data.jslt.Parser;
import com.schibsted.spt.data.jslt.Expression;

JsonNode input = ...;
Expression jslt = Parser.compileString(transform);
JsonNode output = jslt.apply(input);
```

All that's missing here is to parse the incoming JSON, and serialize it.

**Comment by kiddo-7** [comment]
Yes , I can give a brief explanation this "JsonNode input = ...; " is given as a header to my api with as POST request and I need to process the " JsonNode input " and return the new transformed json.

**Comment by larsga** [comment]
Okay. I've never used Dropwizard myself, so I don't know how to do it. It should be pretty easy to find out, though. Just look at some Dropwizard documentation.

**Comment by kiddo-7** [comment]
Okay I will find it.
