### ISSUE TITLE
Getting this error while trying to convert using my jslt template 

### ISSUE THREAD

**Issue by Sravanksk** [schibsted/jslt#91]
com.schibsted.spt.data.jslt.JsltException: Parse error: Encountered "<EOF>" at line 1, column 20.
! Was expecting:
!     "(" ...
! at com.schibsted.spt.data.jslt.parser.ParserImpl.compileExpression(ParserImpl.java:61)
! at com.schibsted.spt.data.jslt.Parser.compile(Parser.java:225)
! at com.schibsted.spt.data.jslt.Parser.compileString(Parser.java:86)
! at com.schibsted.spt.data.jslt.Parser.compileString(Parser.java:74)

My Java Code :: 

public class JsonTransformerResource {
    public static final String SOURCE_JSLT_RESOURCE = "template.jslt";
public JsonNode jsltDemo(final JsonNode Transformer) {
        JsonNode input = Transformer;
        Expression jslt = Parser.compileString("SOURCE_JSLT_RESOURCE");
        return jslt.apply(new ObjectMapper().valueToTree(Transformer));
    }
}

**Comment by larsga** [comment]
This method

`Parser.compileString("SOURCE_JSLT_RESOURCE");`

expects the string to contain the JSLT expression. So you're trying to parse `"SOURCE_JSLT_RESOURCE"`. Clearly that doesn't work.

**Comment by Sravanksk** [comment]
I have a template.jslt file with some defined jslt transformation functions how to invoke my file to parse incoming json objects. Need help ?

**Comment by larsga** [comment]
You'll probably be better off with:

`Parser.compile(new File("/path/to/file.jslt"))`

**Comment by Sravanksk** [comment]
Thanks @larsga . This thing worked.

**Comment by sahilsh1** [comment]
def print_padb_attrib(record)
    if($record != null)
    {
           for ($record)
            .key : { "values" :
             [for(.value)
             if(contains("uom",.)){
             let spl = split(.,",")
             let value = split($spl[0],":")
             let uom =   split($spl[1],":")
             "locale" : get_locale(.),
             "value":$value[1],
             "uom":$uom[1]
             }

             else {
               let spl = split(.,",")
               let value = split($spl[0],":")
               let defaultLocale = $locale 
               if(contains("LanguageCode",.))
                   defaultLocale = get_locale(.LanguageCode)
               "locale" : defaultLocale,
                "value" : $value[1]
               }
      ]
      } }else {}         ------whats wrong in this <'*', '/'>, <'+', '-'>, <'==', '!=', '>=', '>', '<', '<='>, <'|'>, <def function-name()...>, <expression>, <let variable-name = ...>, JsltTokenType.AND or JsltTokenType.OR expected, got ']  getting this how to debug this

**Comment by larsga** [comment]
When you run into this kind of problem it helps to try to simplify the expression by finding parts you can take out without the error going away. Or, the other way around, remove things and see what makes the error go away.

The problem is this bit:

```
{
           let spl = split(.,",")
           let value = split($spl[0],":")
           let defaultLocale = $locale 
           if(contains("LanguageCode",.))
               defaultLocale = get_locale(.LanguageCode)
           "locale" : defaultLocale,
            "value" : $value[1]
           }
```

You start an object with `{`, which is fine. Then three `let`s, also fine.

Then comes an `if`, but what's that doing in the middle of the object? I can't even tell what it's supposed to mean.

After the `if` you have two `key : value` pairs that look fine, except you forgot a `$` on a variable in the first one.

**Comment by larsga** [comment]
Also, *please* don't reuse unrelated issues for new problems. Open a new issue.
