### ISSUE TITLE
Is it possible to give JSLT template along with JSON data as a payload to the POST request and do processing on the data ? 

### ISSUE THREAD

**Issue by Sravanksk** [schibsted/jslt#92]
Payload Format :: 
{
     [
      {
           "key1" : "value1",
          "key2" : "value2"
      },
      {
           "key3" : "value3",
          "key4" : "value4"
      },
      {
           "key5" : "value5",
          "key6" : "value6"
      }
     ] ,
      template:{template.jslt}
}

**Comment by larsga** [comment]
It's possible. Just pick the JSLT out of the incoming request, call `Parser.compileString` on the JSLT template, then process the JSON with the `Expression` that you get from `compileString`. 

That's how the [demo playground](http://spt-data-dev-public-web.s3-website-eu-west-1.amazonaws.com/jstl2.html) works.

See [the code](https://github.com/schibsted/jslt/blob/master/src/main/java/com/schibsted/spt/data/jslt/impl/lambda/LambdaFunction.java).

**Comment by Sravanksk** [comment]
Sure I will try this thing.

**Comment by Sravanksk** [comment]
@larsga but this LambdaFunction.java only accepts a single JSON object , It fails to process data when a list of JSON objects are given. How to overcome this issue.

**Comment by Sravanksk** [comment]
JSLT Template :: 
{
"test" : .TEST,
"test2" : .TEST2,
"test3" : .TEST3,
"test4" : .TEST4
}
Input JSON Objects :: 

[ { 
"TEST"  : "Value1" , 
"TEST2" : "Value2"
} , 
{
"TEST3" : "Value3",
"TEST4" : "Value4"
}
]

This is returning  empty JSON ::   { }

**Comment by larsga** [comment]
The reason is that your two sub-objects are inside an array. This would work:

```
{
"test" : .[0].TEST,
"test2" : .[0].TEST2,
"test3" : .[1].TEST3,
"test4" : .[1].TEST4
}
```

**Comment by larsga** [comment]
>  but this LambdaFunction.java only accepts a single JSON object , It fails to process data when a list of JSON objects are given. How to overcome this issue.

Traverse through the list and apply the expression to each object?

Or parse the list into a JSON array of objects, and use the template to transform the array?

**Comment by Sravanksk** [comment]
> The reason is that your two sub-objects are inside an array. This would work:
> 
> ```
> {
> "test" : .[0].TEST,
> "test2" : .[0].TEST2,
> "test3" : .[1].TEST3,
> "test4" : .[1].TEST4
> }
> ```

What I got after running the above JSLT template -- > 
{
  "test" : "Value1",
  "test2" : "Value2",
  "test3" : "Value3",
  "test4" : "Value4"
}

I should get individual transformation for the JSON in the array 
{
  "test" : "Value1",
  "test2" : "Value2"
},
{
  "test3" : "Value3",
  "test4" : "Value4"
}

**Comment by Sravanksk** [comment]
I used this one , but need something different

    import com.schibsted.spt.data.jslt.Parser;
    import com.schibsted.spt.data.jslt.Expression;
    import com.schibsted.spt.data.jslt.impl.NodeUtils;
    import javax.ws.rs.Consumes;
    import javax.ws.rs.POST;
    import javax.ws.rs.Path;
    import javax.ws.rs.Produces;
    import javax.ws.rs.core.MediaType;

    @POST
    @Path("/data")
    public String getData(Object json) {
        try {
            // this must be:
            // {"json" : ..., "jslt" : jslt}
            JsonNode input = NodeUtils.mapper.readTree("");

            // now we can do the thing
            JsonNode source = NodeUtils.mapper.readTree(input.get("json").asText());

            JsonToken jslt = input.get("jslt").asToken();

            Expression template = Parser.compileString(String.valueOf(jslt));
            JsonNode output = template.apply(source);
            return NodeUtils.mapper.writerWithDefaultPrettyPrinter().writeValueAsString(output);
        } catch (Throwable e) {
            return "Error is : " + e;
        }
    }

Need to change the above code to get the following output :: 

The body of this POST request contains the following payload :: 

Payload :: 

    { "data" : 
           [
                {
                  "Data-1": "Test1",
                  "Data-2" : "Test2",
                  "Data-3" : "Test3"
                }, 
                {
                  "Data-1": "Test1",
                  "Data-2" : "Test2",
                  "Data-3" : "Test3"
                }, 
                {
                  "Data-1": "Test1",
                  "Data-2" : "Test2",
                  "Data-3" : "Test3"
                 }
           ] , "template" : {"jslt-template.jslt"}
    }

Expected Output ::  This must return Array of JSON - Objects by just changing the key names -- > 

JSLT template I've used :: 
    template.jslt -- > 
    
    {
        "New-Key1" : ."Data-1" , 
        "New-Key2" : ."Data-2" , 
        "New-Key3" : ."Data-3"
    }

Expected Response From the POST Request :: 
        
           [
                {
                  "NewKey1": "Test1",
                  "NewKey2" : "Test2",
                  "NewKey3" : "Test3"
                }, 
                {
                  "NewKey1": "Test1",
                  "NewKey2" : "Test2",
                  "NewKey3" : "Test3"
                }, 
                {
                  "NewKey1": "Test1",
                  "NewKey2" : "Test2",
                  "NewKey-3" : "Test3"
                 }
           ]

**Comment by larsga** [comment]
If you change your template to be a loop this will work:

```
[for (.)
{
    "New-Key1" : ."Data-1" , 
    "New-Key2" : ."Data-2" , 
    "New-Key3" : ."Data-3"
}
]
```

The outermost part will take the array it receives, and create one object for each value in the array, using the `{ ... }` part.

**Comment by Sravanksk** [comment]
Yes , This is working , but the body in POST request contains this 

{
"json":
	"{\n\"TEST\" : \"Test-Value\",\n\"CHECK\" : \"Check-Value\"\n}",

"jstl":
	"{\n \"test\" : .TEST,\n \"check\": .\"CHECK\"\n}\n"
}
Can we make the above LambdaFunction code accept a payload similar to this :: 

{ "json" : 
       [
            {
              "Data-1": "Test1",
              "Data-2" : "Test2",
              "Data-3" : "Test3"
            }, 
            {
              "Data-1": "Test1",
              "Data-2" : "Test2",
              "Data-3" : "Test3"
            }, 
            {
              "Data-1": "Test1",
              "Data-2" : "Test2",
              "Data-3" : "Test3"
             }
       ] , "jstl" : {"jslt-template.jslt"}
}

**Comment by catull** [comment]
@Sravanksk Why does the payload know which JSTL template should be used ?

**Comment by catull** [comment]
@Sravanksk So, essentially, the client knows exactly which JSTL templates are available, why ?
Also, you are compiling the same JSTL template over and over.  Not a choice I would make.

**Comment by Sravanksk** [comment]
@catull @larsga , If the client want to compile a new JSLT template for every request , how to do it ? Is that possible ? That is the actual problem I have ?

**Comment by catull** [comment]
The JSTL resides on the server.
You have 2 options.

- Pass the entire JSTL logic in the JSON payload.
- Keep the payload simple, let the server deal with the JSTL logic, hidden from the caller

Option 1 is dangerous, the caller could do all sorts of data manipulation.

Option 2 is cleaner.  But it only allows one data conversion / transformation.

**Comment by catull** [comment]
@Sravanksk Your requirements are not entirely clear, I am afraid.

I'd say, every time your payload changes (i.e. a new attribute / node etc), potentially your conversion / transformation is affected.
You are going to have to modify the JSTL logic.

**Comment by Sravanksk** [comment]
Payload given :: 
Payload:  
{data : 
   [
       {......balance:”(-343.20$)”, "date:”20/08/2018 9:30 pm”,Mobile_Number:”XXXXXX4324” }....
   ] , 
 template:{JSLT template}}

And this JSLT template will be sent by the client only.
Here we cannot expect the payload to be the same always , so how can we make these transformation

**Comment by catull** [comment]
Here's what I suggest.

Keep an `Expression` attribute in the class `LambdaFunction`.

Initialise it in the constructor of `LambdaFunction`:
```java
@Path("/api")
 public class LambdaFunction {

  private Expression template;

  public LambdaFunction() {
    template = Expression template = Parser.compileString(jslt);
  }

  /**
   * Transform the incoming JSON with JSLT and return the result.
   */
  @POST
  @Path("/json-post")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.APPLICATION_JSON)
  public String invoke(String json) {
    try {
        // this must be:
        // {"json" : ..., "jslt" : jslt}
        JsonNode input = NodeUtils.mapper.readTree(json);

        // now we can do the thing
        JsonNode source = NodeUtils.mapper.readTree(input.get("json").asText());
        JsonNode output = template.apply(source);

        return NodeUtils.mapper.writerWithDefaultPrettyPrinter().writeValueAsString(output);
    } catch (Throwable e) {
        return "ERROR: " + e;
    }
  }

 // Rest of the class
}
```

This way, the template get compiled once per `LambdaFunction` instance.

**Comment by catull** [comment]
By the way, do you use jackson or a similar serialisation library ?
All this low-level String manipulation is not type-safe.

**Comment by Sravanksk** [comment]
I use jackson , but this is weird , why those " \n " things in the request , If I try to remove them then its throwing some errors.

{
"json":
"{\n"TEST" : "Test-Value",\n"CHECK" : "Check-Value"\n}",

"jstl":
"{\n "test" : .TEST,\n "check": ."CHECK"\n}\n"
}

**Comment by catull** [comment]
In that case, I suggest a radically cleaner approach.

Let `jackson` handle the low-level serialisation.
Specify the input and output types, thus, e.g.

```java
  @POST
  @Path("/json-post")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.APPLICATION_JSON)
  public ResponseType invoke(RequestType request) {
    try {
        // Convert the RequestType to String, with ObjectMapper
        String json = ......
        JsonNode input = NodeUtils.mapper.readTree(json);

        // now we can do the thing
        JsonNode source = NodeUtils.mapper.readTree(input.get("json").asText());
        JsonNode output = template.apply(source);

        // Convert JsonNode to ResponseType, not to String
        return NodeUtils.mapper.writerWithDefaultPrettyPrinter().writeValueAsString(output);
    } catch (Throwable e) {
        return "ERROR: " + e;
    }
  }
```

And, keep the JSTL logic on the server side.

So that your payload is just the `RequestType`, the input paramater.
