### ISSUE TITLE
How to change this code to accept data in the following format ? I tried a lot but couldn't find any relevant things.

### ISSUE THREAD

**Issue by Sravanksk** [schibsted/jslt#93]
@Path("/api")
    public class LambdaFunction {

    /**
     * Transform the incoming JSON with JSLT and return the result.
     */
    @POST
    @Path("/json-post")
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    public String invoke(String json) {
        try {
            // this must be:
            // {"json" : ..., "jslt" : jslt}
            JsonNode input = NodeUtils.mapper.readTree(json);

            // now we can do the thing
            JsonNode source = NodeUtils.mapper.readTree(input.get("json").asText());
            String jslt = input.get("jstl").asText();

            Expression template = Parser.compileString(jslt);
            JsonNode output = template.apply(source);
            return NodeUtils.mapper.writerWithDefaultPrettyPrinter().writeValueAsString(output);
        } catch (Throwable e) {
            return "ERROR: " + e;
        }
    }

    }

Instead of taking data in this format :: 

{"json":"[{\"Key1\": \"Value1\", \"Key2\": \"Value2\", \"Key3\": \"Value3\"},{\"Key1\": \"Value1\", \"Key2\": \"Value2\", \"Key3\": \"Value3\"},{\"Key1\": \"Value1\", \"Key2\": \"Value2\", \"Key3\": \"Value3\"}]","jstl":"\n[\nfor (.)\n{\n \"Key-Change-1\" : .Key1,\n \"Key-Change-2\": .\"Key2\",\n \"Key-Change-3\" : .\"Key3\"\n}\n]\n"}

Can we take data only in JSON format without those "   \ and \n    " 
{"json": ["key":"value" , "key":"value" , "key":"value"] , "jslt":["jstl-template"]}

[ I need to accept the "json" and "jstl" as an Array of JSON objects instead of string ] , and I need to POST this data to an API so sending data in the above format with " \ and \n " format is not fair.

**

I want to pass it as POST payload something like: {"json": "json values", "jstl":"jstl values"}

**

 @larsga 
@catull

**Comment by catull** [comment]
@Sravanksk A word of advise, try to layout your code / payload snippets with proper markup.
Your last comment above is hard to read.

**Comment by catull** [comment]
I already explained to you an approach in a different issue, which you closed.

If you do not think it is of value, do not expect me to repeat myself here.

Your approach is unorthodox, if I dare say, you are trying to force a square peg into a round hole.

In other words, you are going to great lengths to use an over-complicated solution.

Eventually, you will succeed.
At the cost of the square peg having its corners forced off, and the round hole not being perfectly circular.

Also, did you study the following resources, mentioned in [Readme.md](https://github.com/schibsted/jslt/blob/master/README.md) ?

- [Playground](http://spt-data-dev-public-web.s3-website-eu-west-1.amazonaws.com/jstl2.html)
- [Language tutorial](https://github.com/schibsted/jslt/blob/master/tutorial.md)
- [Function API](https://github.com/schibsted/jslt/blob/master/functions.md)
- [Examples](https://github.com/schibsted/jslt/blob/master/examples/README.md)

**Comment by Sravanksk** [comment]
@catull  , This issue is solved , thanks for your suggestions.
