### ISSUE TITLE
Can this be simplified ?

### ISSUE THREAD

**Issue by catull** [schibsted/jslt#97]
I have this input
```json
{
  "header": {
    "language": "fr",
    "titles": [
      {
        "locale": "de",
        "name": "Deutscher Titel Text"
      },
      {
        "locale": "en",
        "name": "English title text"
      },
      {
        "locale": "fr",
        "name": "Texte de titre français"
      },
      {
        "locale": "it",
        "name": "Testo di titolo italiano"
      }
    ]
  }
}
```
`header.language` is any one of the title locales: "de", "en", "fr" or "it".
Default is "de".

I want to use the language-specific title.

Can this be simplified ?
```
let let lang   = .header.language

def getTitle ()
  if (.header.titles[0].locale == $lang)
    .header.titles[0].name
  else if (.header.titles[1].locale == $lang)
    .header.titles[1].name
  else if (.header.titles[2].locale == $lang)
    .header.titles[2].name
  else
    .header.titles[3].name
```

**Comment by larsga** [comment]
Like this?

```
let lang = "fr"
[for (.header.titles) .name if (.locale == $lang)]
```

I recommend letting `lang` be the parameter to the function.

Note that for expressions do not allow you to tack on array indexing on the end, but you can assign to a variable, then do `$variable[0]`

**Comment by catull** [comment]
This works:
```json
{ "title": getTitle ()[0] }
```
with
```
let let lang   = .header.language  // $lang is used in various places and `def`s.

def getTitle ()
  [for (.header.titles) .name if (.locale == $lang)]
```

Why do you recommend having
```json
{ "title": getTitle (.header.language)[0] }
```
with
```
```
def getTitle (lang)
  [for (.header.titles) .name if (.locale == $lang)]
```

**Comment by larsga** [comment]
The `lang` is effectively a parameter to the function. Not very flexible to have it bound to a global variable, and very prone to shooting yourself in the foot. It's just very bad practice.

**Comment by catull** [comment]
Thanks, will consider it from now on.
