### ISSUE TITLE
Parsing issue when defining a variable prior a for-loop

### ISSUE THREAD

**Issue by jbenoit2011** [schibsted/jslt#98]
Hi, I found a parsing error while doing experiment on your [playground](http://spt-data-dev-public-web.s3-website-eu-west-1.amazonaws.com/jstl2.html):

JSLT:
```
let user_id = .user_id
let timestamp = .timestamp

[for (.event_properties.home_ids) {"home_id": ., "user_id": $user_id, "time": format-time($timestamp,"YYYY-MM-DD HH:mm:ss")}]
```

Input:
```
{
  "id": "bbb6241b-7216-4b88-9995-fd4231520f0a",
  "timestamp": 1516021153,
  "name": "home-search-results-viewed",
  "source": "front",
  "browser": {
    "page": {
      "url": "http://foo.bar"
    }
  },
  "user_id": 10,
  "event_properties": {
    "home_ids": [
      1,
      2,
      3
    ]
  }
}
```

Actual output:
```
ERROR: com.schibsted.spt.data.jslt.JsltException: Parse error: Encountered " "for" "for "" at line 4, column 2.
Was expecting one of:
    "null" ...
    <INTEGER> ...
    <DECIMAL> ...
    <STRING> ...
    "[" ...
    ":" ...
    "{" ...
    "true" ...
    "false" ...
    "." ...
    "if" ...
    "(" ...
    <IDENT> ...
    <PIDENT> ...
    <VARIABLE> ...
     at <inline>:4:1
```

Expected output:
```
[ {
  "home_id" : 1,
  "user_id" : 10,
  "time" : "2018-01-15 12:59:13"
}, {
  "home_id" : 2,
  "user_id" : 10,
  "time" : "2018-01-15 12:59:13"
}, {
  "home_id" : 3,
  "user_id" : 10,
  "time" : "2018-01-15 12:59:13"
} ]
```

I found a workaround by adding `let x = "x"` just before the for-loop, giving the following JSLT:
```
let user_id = .user_id
let timestamp = .timestamp
let x = "x"

[for (.event_properties.home_ids) {"home_id": ., "user_id": $user_id, "time": format-time($timestamp,"YYYY-MM-DD HH:mm:ss")}]
```

Thanks.

Julien.

**Comment by larsga** [comment]
From the user perspective, this is clearly a bug.

The simplest workaround is to write:

`let timestamp = (.timestamp)`

I will definitely consider this.

**Comment by modernwarfareuplink** [comment]
**let user_id = .user_id
let timestamp = .timestamp

let result = [for (.event_properties.home_ids) {"home_id": ., "user_id": $user_id, "time": format-time($timestamp,"YYYY-MM-DD HH:mm:ss")}]
$result**

This should also work, incase you do not want to use the  `let timestamp = (.timestamp)`
@jbenoit2011

**Comment by larsga** [comment]
This is the same as issue #133, which is scheduled for the next release.
